<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Lesson 22: Simple Linear Regression</title>

<script src="site_libs/header-attrs-2.7/header-attrs.js"></script>
<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cerulean.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>





<link rel="stylesheet" href="styles.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Math 221</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Unit 1
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="Lesson01_Campus.html">Lesson 1: (On Campus) Course Intro &amp; Probability</a>
    </li>
    <li>
      <a href="Lesson01.html">Lesson 1: (Online) Course Intro &amp; Probability</a>
    </li>
    <li>
      <a href="Lesson02.html">Lesson 2: The Statistical Process</a>
    </li>
    <li>
      <a href="Lesson03.html">Lesson 3: Describing Quantitative Data (Shape &amp; Center)</a>
    </li>
    <li>
      <a href="Lesson04.html">Lesson 4: Describing Quantitative Data (Spread)</a>
    </li>
    <li>
      <a href="Lesson05.html">Lesson 5: Normal Distributions</a>
    </li>
    <li>
      <a href="Lesson06.html">Lesson 6: The Central Limit Theorem</a>
    </li>
    <li>
      <a href="Lesson07.html">Lesson 7: Calculating Probabilities involving the Sample Mean</a>
    </li>
    <li>
      <a href="Lesson08.html">Lesson 8: Unit 1 Review</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Unit 2
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="Lesson09.html">Lesson 9: Hypothesis Test for One Mean (Sigma Known)</a>
    </li>
    <li>
      <a href="Lesson10.html">Lesson 10: Confidence Interval for One Mean (Sigma Known)</a>
    </li>
    <li>
      <a href="Lesson11.html">Lesson 11: Inference for One Mean (Sigma Unknown)</a>
    </li>
    <li>
      <a href="Lesson12.html">Lesson 12: Inference for Match Pairs</a>
    </li>
    <li>
      <a href="Lesson13.html">Lesson 13: Inference for Two Independent Samples</a>
    </li>
    <li>
      <a href="Lesson14.html">Lesson 14: Inference for Several Independent Samples</a>
    </li>
    <li>
      <a href="Lesson15.html">Lesson 15: Unit 2 Review</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Unit 3
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="Lesson16.html">Lesson 16: Describing Categorical Data</a>
    </li>
    <li>
      <a href="Lesson17.html">Lesson 17: Inference for One Proportion</a>
    </li>
    <li>
      <a href="Lesson18.html">Lesson 18: Inference for Two Proportions</a>
    </li>
    <li>
      <a href="Lesson19.html">Lesson 19: Inference for Independence of Categorical Data</a>
    </li>
    <li>
      <a href="Lesson20.html">Lesson 20: Unit 3 Review</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Unit 4
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="Lesson21.html">Lesson 21: Describing Bivariate Data</a>
    </li>
    <li>
      <a href="Lesson22.html">Lesson 22: Simple Linear Regression</a>
    </li>
    <li>
      <a href="Lesson23.html">Lesson 23: Inference for Bivariate Data</a>
    </li>
    <li>
      <a href="Lesson24.html">Lesson 24: Unit 4 Review</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="RHelp.html">R Help</a>
</li>
<li>
  <a href="Data.html">Data</a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Lesson 22: Simple Linear Regression</h1>

</div>

<div id="TOC">
<ul>
<li><a href="#lesson-outcomes">Lesson Outcomes</a></li>
<li><a href="#introduction-to-regression">Introduction to Regression</a></li>
<li><a href="#case-study-supercroc">Case Study: SuperCroc</a>
<ul>
<li><a href="#r-instructions-for-performing-a-linear-regression">R Instructions for Performing a Linear Regression</a></li>
<li><a href="#interpreting-the-regression-output">Interpreting the Regression Output</a></li>
<li><a href="#predictions">Predictions</a></li>
<li><a href="#r-instructions-for-graphing-the-regression-line">R Instructions for Graphing the Regression Line</a></li>
</ul></li>
<li><a href="#case-study-manatees-and-powerboats">Case Study: Manatees and Powerboats</a>
<ul>
<li><a href="#regression-equation">Regression Equation</a></li>
<li><a href="#interpreting-the-regression-output-1">Interpreting the Regression Output</a></li>
<li><a href="#predictions-1">Predictions</a></li>
<li><a href="#drawing-the-regression-line-on-a-scatterplot">Drawing the Regression Line on a Scatterplot</a></li>
</ul></li>
<li><a href="#introduction-to-multiple-regression">Introduction to Multiple Regression</a></li>
<li><a href="#whats-in-a-name">What’s in a Name?</a></li>
<li><a href="#summary">Summary</a></li>
<li><a href="#navigation">Navigation</a></li>
</ul>
</div>

<script type="text/javascript">
 function showhide(id) {
    var e = document.getElementById(id);
    e.style.display = (e.style.display == 'block') ? 'none' : 'block';
 }
</script>
<div style="float:right;width=40%;">
<br/>
<div style="padding-left:10%;">
<strong>Optional Lesson Video</strong>
</div>
<iframe width="90%" align="right" src="https://www.youtube.com/embed/zlX2v7F0hhY?list=PLaZryQtbPQC-cf5OWjLW7bqFjhgmQAApJ" frameborder="1" allow="autoplay; encrypted-media" allowfullscreen>
</iframe>
</div>
<div id="lesson-outcomes" class="section level2">
<h2>Lesson Outcomes</h2>
<a href="javascript:showhide('oc')"><span style="font-size:8pt;">Show/Hide Outcomes</span></a>
<div id="oc" style="display:none;">
<p>By the end of this lesson, you should be able to:</p>
<ul>
<li>Identify the explanatory and response variable in a study.</li>
<li>Calculate the slope and intercept of a regression model.</li>
<li>Interpret the slope of the regression model.</li>
<li>Make predictions using a regression model.</li>
</ul>
</div>
<p><br></p>
<div style="clear:both;">

</div>
<p><br/></p>
</div>
<div id="introduction-to-regression" class="section level2">
<h2>Introduction to Regression</h2>
<p>Simple linear regression is a method used to fit a line to data. This provides a powerful tool to model bivariate data (i.e., data involving two variables.) Regression allows us to write a linear equation that models the relationship between the <strong>independent variable</strong> (<span class="math inline">\(X\)</span>) and the <strong>dependent variable</strong> (<span class="math inline">\(Y\)</span>) which we can use to predict the value of <span class="math inline">\(Y\)</span> for any given value of <span class="math inline">\(X\)</span>. Sometimes the independent variable is also called the <strong>explanatory variable</strong>, and the dependent variable is also called the <strong>response variable</strong>.</p>
<p>We will be using linear equations throughout this lesson. Click on the link below if you would like to review lines and linear equations.</p>
<!-- BEGIN REVIEW OF LINES  ***********************************************  -->
<a href="javascript:showhide('re')"><span style="font-size:8pt;">Click Here for a Review of the Equation of a Line</span></a>
<div id="re" style="display:none;">
<p><strong>Linear Equations</strong></p>
<p>A <strong>linear equation</strong> is the technical term for any equation that describes a line. Two important characteristics of a line are its slope and its Y-intercept.</p>
<p>The <strong>Y-intercept</strong> is the value at which the line crosses the Y-axis. Stated differently, the Y-intercept is the value of <span class="math inline">\(Y\)</span> that corresponds to <span class="math inline">\(X = 0\)</span>. Given the equation of a line, you can find the Y-intercept by substituting <span class="math inline">\(X = 0\)</span> and solving for <span class="math inline">\(Y\)</span>.</p>
<p>The <strong>slope</strong> of a line is a measure of how steep the line is. It is sometimes described as <em>rise</em> over <em>run</em>. If the slope is positive, then the values of <span class="math inline">\(Y\)</span> increase as the values of <span class="math inline">\(X\)</span> increase. When the slope is expressed as a fraction, the numerator tells how much the points on the line change vertically as you move to the right the distance indicated by the denominator. If the slope is negative, the values of <span class="math inline">\(Y\)</span> decrease as <span class="math inline">\(X\)</span> increases. If the slope of a line is <span class="math inline">\(\frac{2}{3}\)</span>, then the value of <span class="math inline">\(Y\)</span> will increase by 2 units if <span class="math inline">\(X\)</span> increases by three units. For a line with slope <span class="math inline">\(-5 \left( = \frac{-5}{1}\right)\)</span>, the value of <span class="math inline">\(Y\)</span> will <em>decrease</em> by 5 units if <span class="math inline">\(X\)</span> increases by one unit.</p>
<p>To describe a line, we need two pieces of information. If we know the slope and the Y-intercept, these two values uniquely determine the line. In this course, we will focus the <strong>slope-intercept form</strong> of a line. The equation of a line in slope-intercept form is often written as: <span class="math display">\[Y = m X + b\]</span> where <span class="math inline">\(Y\)</span> is the dependent variable, <span class="math inline">\(X\)</span> is the independent variable, <span class="math inline">\(m\)</span> is the slope of the line, and <span class="math inline">\(b\)</span> is the Y-intercept.</p>
<div class="QuestionsHeading">
Answer the following questions:
</div>
<div class="Questions">
<p>A. If the equation of a line is <span class="math inline">\(Y = 3 X - 2\)</span>, where does it cross the Y-axis?</p>
<a href="javascript:showhide('A')"><span style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="A" style="display:none;">
<ul>
<li>At <span class="math inline">\(-2\)</span></li>
</ul>
</div>
<p><br></p>
<p>B. If the equation of a line is <span class="math inline">\(Y = 3 X - 2\)</span>, what happens to the value of <span class="math inline">\(Y\)</span> as <span class="math inline">\(X\)</span> increases?</p>
<a href="javascript:showhide('B')"><span style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="B" style="display:none;">
<ul>
<li>The value of <span class="math inline">\(Y\)</span> increases by 3 as <span class="math inline">\(X\)</span> increases by 1.<br />
</li>
</ul>
</div>
<p> </p>
</div>
<p><br></p>
</div>
<p><br> <!-- END REVIEW OF LINES ***********************************************  --></p>
<p>In statistics, we may use different notation than you encountered in your algebra classes. We use different symbols to denote the slope and Y-intercept than you may have seen before. In your algebra class, you may have written the equation of a line as <span class="math inline">\(Y = mX + b\)</span>, where <span class="math inline">\(m\)</span> is the slope and <span class="math inline">\(b\)</span> is the Y-intercept. We represent the Y-intercept with the symbol <span class="math inline">\(b_0\)</span> and the slope with the symbol <span class="math inline">\(b_1\)</span>. In addition, we often write the Y-intercept as the first part of this equation.</p>
<!--
Notice that this is the equation of a straight line. You might have written linear equations in the form $Y=mX+b$ in your algebra classes.  Notice that our equation has the same form.  The slope is given by $b_1$ and the $Y$-intercept is given by $b_0$.
-->
<p>This leads to the following representation of the linear equation: <span class="math display">\[\hat Y = b_0 + b_1 X\]</span> We use the symbol <span class="math inline">\(\hat Y\)</span> to indicate a predicted value for <span class="math inline">\(Y\)</span>. The value <span class="math inline">\(b_0\)</span> is the Y-intercept and <span class="math inline">\(b_1\)</span> is the slope. Compare this notation to traditional slope-intercept form.</p>
<p>You may wonder why we would use this form (rather than traditional slope-intercept form) to express the equation. Click on the link below for a brief explanation if you are interested.</p>
<!-- START EXPLANATION OF FORM ***********************************************  -->
<a href="javascript:showhide('ex')"><span style="font-size:8pt;">Click Here for an Explanation</span></a>
<div id="ex" style="display:none;">
<p>In this course we will relate one independent variable to one dependent variable. In many cases, we will want to predict the value of <span class="math inline">\(Y\)</span>, based on the value of <span class="math inline">\(X\)</span>. This is done using simple linear regression.<br />
If there are several independent variables that influence the value of the dependent variable, we call it multiple regression. A multiple regression equation with two independent variables, <span class="math inline">\(X_1\)</span> and <span class="math inline">\(X_2\)</span>, could be written as: <span class="math display">\[Y = b_0 + b_1 X_1 + b_2 X_2\]</span> If there were four independent variables, we would have the regression equation <span class="math display">\[Y = b_0 + b_1 X_1 + b_2 X_2 + b_3 X_3 + b_4 X_4\]</span> Notice that the Y-intercept is the first term in this sum, and we can simply add more terms as needed. The reason we write the Y-intercept first is that it allows us to easily add more terms to the model without having to rewrite or reorder any of the existing terms. In this course, you will not be conducting multiple regression analyses, but it is good for you to be aware that these procedures exist. Multiple regression is used in many business forecasting models.</p>
<div class="QuestionsHeading">
Answer the following questions:
</div>
<div class="Questions">
<p>A. For the linear regression equation, <span class="math inline">\(Y = 1.2 - 3.4 X\)</span>, what is the slope?</p>
<a href="javascript:showhide('a2')"><span style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="a2" style="display:none;">
<ul>
<li>slope = <span class="math inline">\(-3.4\)</span></li>
</ul>
</div>
<p><br></p>
<p>B. For the linear regression equation, <span class="math inline">\(Y = 1.2 - 3.4 X\)</span>, what is the Y-intercept?</p>
<a href="javascript:showhide('b2')"><span style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="b2" style="display:none;">
<ul>
<li>y-intercept = <span class="math inline">\(1.2\)</span></li>
</ul>
</div>
<p><br></p>
<p>C. If a line crosses the Y-axis at <span class="math inline">\(-3\)</span> and has a slope of <span class="math inline">\(\frac{5}{2}\)</span>, how would you write the equation of this line in slope-intercept form?</p>
<a href="javascript:showhide('c2')"><span style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="c2" style="display:none;">
<center>
<span class="math inline">\(Y = -3 + \frac{5}{2}X\)</span>
</center>
</div>
<p> </p>
</div>
</div>
<p><br> <br> <!-- END EXPLANATION OF FORM ***********************************************  --></p>
</div>
<div id="case-study-supercroc" class="section level2">
<h2>Case Study: SuperCroc</h2>
<div style="float:right;padding:10px;">
<p><img src="Images/Super_croc.jpeg" width=300px></p>
</div>
<p><img src="Images/Step1.png"></p>
<p>A partial skeleton of an enormous extinct crocodilian was found in the Sahara Desert. With a skull that is about six feet long, this massive creature was a fierce hunter. Unfortunately, the skeleton is incomplete. Almost none of the bones for the legs and tail were recovered. How big was this massive creature?</p>
<p>To answer this question, paleontologist Paul Sereno teamed up with modern crocodile expert Brady Barr. Their work is demonstrated in the National Geographic video <em>SuperCroc</em>. Using linear regression, these researchers are able to estimate the size of SuperCroc simply by knowing the size of its skull. Before continuing, please follow this link to watch a 15 minute clip of this video.</p>
<br>
<div class="message Note">
This video is an hour and a half long. <strong>YOU DO NOT NEED TO WATCH THE ENTIRE VIDEO</strong>. Please watch only the last fifteen minutes, beginning at 1:19:00
</div>
<p><br> <br></p>
<iframe id="kaltura_player_1578605835" src="https://cdnapisec.kaltura.com/p/1157612/sp/115761200/embedIframeJs/uiconf_id/41351812/partner_id/1157612?iframeembed=true&amp;playerId=kaltura_player_1578605835&amp;entry_id=0_kh1juzmd" width="800" height="450" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" frameborder="0">
</iframe>
<p><br/></p>
<p><img src="Images/Step2.png"></p>
<p>We will use Sereno and Barr’s measurements on the lengths of Estuarine, or saltwater, Crocodiles’ heads to estimate the length of their bodies. Their measurements are given in the file <a href="./Data/EstuarineCrocodiles.xlsx">EstuarineCrocodiles.xlsx</a>.</p>
<p><br/></p>
<p><img src="Images/Step3.png"></p>
<p>Using the information we learned in <a href="Lesson21.html#r-instructions-for-scatterplots">Lesson 21</a> we create a scatterplot for the Estuarine Crocodile data.</p>
<pre class="r"><code>plot(EstuarineCrocodiles$BodyLength ~ EstuarineCrocodiles$HeadLength,
     main=&quot;Estuarine Crocodile Measurements&quot;,
     ylab=&quot;Body Length (cm)&quot;,
     xlab=&quot;Head Length (cm)&quot;,
     col=&quot;seagreen&quot;, pch=16)</code></pre>
<p><img src="Lesson22_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<p>Also, using the information we learned in Lesson 21 about <a href="Lesson21.html#r-instructions-for-computing-correlation">computing correlation</a> we obtain the following.</p>
<pre class="r"><code>cor(EstuarineCrocodiles$BodyLength, EstuarineCrocodiles$HeadLength)</code></pre>
<pre><code>## [1] 0.9898911</code></pre>
<p>There is a strong positive linear relationship between these two measurements (<span class="math inline">\(r=0.9899\)</span>). Because of this strong linear relationship, it seemed reasonable to fit a line to the data. This line can be used to predict the length of a crocodile with a known head length. In particular, we will use this line to estimate the length of SuperCroc.</p>
<p><br/></p>
<p><img src="Images/Step4.png"></p>
<p>We can use simple linear regression to develop an equation relating the head length of an estuarine crocodile to its body length. Let <span class="math inline">\(Y\)</span> be the body length (in cm) and <span class="math inline">\(X\)</span> be the head length (in cm).</p>
<p>If we can assume that there is a linear relationship between the head length and the body length, then we can express this symbolically as: <span class="math display">\[
\hat Y = b_0 + b_1 X
\]</span> where <span class="math inline">\(\hat Y\)</span> represents the predicted body length of an estuarine crocodile with a head length of <span class="math inline">\(X\)</span>. The numbers <span class="math inline">\(b_0\)</span> and <span class="math inline">\(b_1\)</span> are called the estimated “regression coefficients”. “Coefficient” is a fancy term that simply means a number, especially a number that is multiplied by a variable such as <span class="math inline">\(X\)</span>. We will use software to calculate the regression coefficients.</p>
<div id="r-instructions-for-performing-a-linear-regression" class="section level3">
<h3>R Instructions for Performing a Linear Regression</h3>
<div class="SoftwareHeading">
R Instructions
</div>
<div class="Software">
<p><strong>To find the estimated regression coefficients (<span class="math inline">\(b_0\)</span> and <span class="math inline">\(b_1\)</span>) in R, do the following:</strong></p>
<ul>
<li>Import the data into RStudio: <a href="./Data/EstuarineCrocodiles.xlsx">EstuarineCrocodiles.xlsx</a></li>
<li>Use the <code>lm( )</code> function to create a “linear model” for the data.</li>
<li>Put your response variable (Y) first, followed by a <code>~</code>, followed by the explanatory variable (X).</li>
<li>Use the <code>summary( )</code> function to view the results of the <code>lm( )</code> function.</li>
<li>The summary shows the “Estimates” for the <code>(Intercept)</code> and the slope term. The <code>(Intercept)</code> estimate is the value of <span class="math inline">\(b_0\)</span> (y-intercept), and the second Estimate is always for the slope term, <span class="math inline">\(b_1\)</span>.</li>
</ul>
<pre class="r"><code>estuarine.lm &lt;- lm(EstuarineCrocodiles$BodyLength ~ EstuarineCrocodiles$HeadLength)
summary(estuarine.lm)</code></pre>
<pre><code>
Call:
lm(formula = EstuarineCrocodiles$BodyLength ~ EstuarineCrocodiles$HeadLength)

Residuals:
     Min       1Q   Median       3Q      Max 
-18.1302  -7.1968  -0.9602   8.2245  25.9486 

Coefficients:
                               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                    -18.2740     9.9663  -1.834   0.0782 .  
EstuarineCrocodiles$HeadLength   7.6601     0.2152  35.588   &lt;2e-16 ***
---
Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1

Residual standard error: 10.8 on 26 degrees of freedom
Multiple R-squared:  0.9799,    Adjusted R-squared:  0.9791 
F-statistic:  1267 on 1 and 26 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>As shown in the summary output above, the value of <span class="math inline">\(b_0 = -18.274\)</span> and the value of <span class="math inline">\(b_1 = 7.6601\)</span>.</p>
<p><br></p>
</div>
<p><br></p>
</div>
<div id="interpreting-the-regression-output" class="section level3">
<h3>Interpreting the Regression Output</h3>
<p>The regression coefficients are given in the column labeled “Estimate”. The “(Intercept)” of -18.2740 in this case, gives the value of <span class="math inline">\(b_0\)</span>. The “Estimate” below the (Intercept) of 7.6601 is the value for the slope, <span class="math inline">\(b_1\)</span>.</p>
<p>The y-intercept gives the mean y-value for when the x-value is zero. It is sometimes called the <em>constant term</em> because it is the term in the equation not multiplied by the value of <span class="math inline">\(x\)</span>. For the crocodile data, <span class="math inline">\(b_0=-18.274\)</span>, which is somewhat of a silly number if we were to interpret it because it is claiming that the mean body length of crocodiles that have head lengths of 0 cm is -18.274 cm. Since a head length of 0 cm is meaningless, it also makes sense that the y-intercept of -18.274 cm is meaningless, so we ignore this value for this data.</p>
<p>The slope gives the value that is to be multiplied by <span class="math inline">\(X\)</span>; this is the slope of the regression equation. In our model, <span class="math inline">\(X\)</span> represents the head length, in centimeters. The slope in our regression equation is <span class="math inline">\(b_1=7.660\)</span>. This number tells us how much the mean y-value (body length) increases as x (head length) increases.</p>
<p><span class="math display">\[
\underbrace{\hat{Y}}_\text{Predicted Body Length} = -18.274 + 7.660 \underbrace{X}_\text{Head Length}
\]</span></p>
<p>We put the “hat” on <span class="math inline">\(Y\)</span> to represent that this is an estimate of the value of <span class="math inline">\(Y\)</span>. For example, with SuperCroc, we don’t know the <em>actual</em> body length, but we can use the equation to come up with a predicted value that is reasonable. The symbol <span class="math inline">\(\hat{Y}\)</span> is read, “<span class="math inline">\(Y\)</span>-hat”. We can also express this equation in the following way: <span class="math display">\[
\hat{BodyLength} = -18.274 + 7.660 \cdot HeadLength
\]</span></p>
<p>The slope of the regression equation is 7.660. This means that for each one-unit increase in <span class="math inline">\(X\)</span>, we expect a corresponding increase in the average of <span class="math inline">\(Y\)</span> of 7.660 centimeters. For every additional centimeter of head length, we expect that the mean body length to increase by 7.660 cm.</p>
<p>The <span class="math inline">\(Y\)</span>-intercept is <span class="math inline">\(-18.274\)</span>. As stated previously it does not make sense to interpret the <span class="math inline">\(Y\)</span>-intercept, so we simply state that it is not interpretable. The <span class="math inline">\(Y\)</span>-intercept is included in the regression equation, even though it may not be interpretable. It must be included to make the predictions more reasonable.</p>
</div>
<div id="predictions" class="section level3">
<h3>Predictions</h3>
<p>An 87 cm skull from a juvenile sarcosuchus (SuperCroc) was discovered. We want to estimate the body length of this crocodilian using the regression equation we calculated for the estuarine crocodiles.</p>
<p>To predict the body length, we can substitute <span class="math inline">\(x=87\)</span> into the regression equation: <span class="math display">\[
\hat Y = -18.274 + 7.660 X = -18.274 + 7.660 (87) = 648.146
\]</span></p>
<p>Note that if a juvinile sarcosuchus has a head length of 87 cm, then the regression equation predicts the body length to be around 648 cm.</p>
</div>
<div id="r-instructions-for-graphing-the-regression-line" class="section level3">
<h3>R Instructions for Graphing the Regression Line</h3>
<div class="SoftwareHeading">
R Instructions
</div>
<div class="Software">
<p><strong>To add a regression line to a scatterplot in RStudio, do the following:</strong></p>
<ul>
<li>Import the data into RStudio: <a href="./Data/EstuarineCrocodiles.xlsx">EstuarineCrocodiles.xlsx</a></li>
<li>Perform the regression:</li>
</ul>
<pre class="r"><code>estuarine.lm &lt;- lm(EstuarineCrocodiles$BodyLength ~ EstuarineCrocodiles$HeadLength)</code></pre>
<ul>
<li>Create the scatterplot and use <code>abline( )</code> with the name of your regression, <code>estuarine.lm</code> in this case, to graph the regression line.</li>
</ul>
<pre class="r"><code>plot(EstuarineCrocodiles$BodyLength ~ EstuarineCrocodiles$HeadLength,
     main=&quot;Estuarine Crocodile Measurements&quot;,
     ylab=&quot;Body Length (cm)&quot;,
     xlab=&quot;Head Length (cm)&quot;,
     col=&quot;seagreen&quot;, pch=16)

abline(estuarine.lm)</code></pre>
<p><img src="Lesson22_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p><br/></p>
</div>
<p><br/></p>
<p>If you looked carefully at the scatterplot shown above you might realize that the x-axis of the graph only goes up to 60 cm. The juvenile sarcosuchus we were using to make predictions had a head lenght of 87 cm, which is way off the chart! Further, the estimated body length our regression predicts for this juvenile sarcosuchus is over six and a half meters long! That is over 21 feet! Imagine how big it might have been if it reached maturity! Further, to actually draw the prediction on our graph we would need to use the <code>xlim=c(0,90)</code> and <code>ylim=c(0,650)</code> commands inside the <code>plot( )</code> function.</p>
<pre class="r"><code>plot(EstuarineCrocodiles$BodyLength ~ EstuarineCrocodiles$HeadLength,
     main=&quot;Estuarine Crocodile Measurements&quot;,
     ylab=&quot;Body Length (cm)&quot;,
     xlab=&quot;Head Length (cm)&quot;,
     col=&quot;seagreen&quot;, pch=16,
     xlim=c(0,90),
     ylim=c(0,650))

abline(estuarine.lm)

points(87, 648, pch=16, cex=1.2, col=&quot;orange&quot;)
text(87,648, &quot;Predicted Body Length of 648 cm&quot;, pos=2)</code></pre>
<p><img src="Lesson22_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<div class="QuestionsHeading">
Answer the following question:
</div>
<div class="Questions">
<ol style="list-style-type: decimal">
<li>The fossil of the mature specimen of sarcosuchus had a head length of 160 cm. Using the linear regression equation, how long would we predict the body would be?</li>
</ol>
<p><a href="javascript:showhide('Q1')"><span style="font-size:8pt;">Show/Hide Solution</span></a></p>
<div id="Q1" style="display:none;">
<p>Using the regression equation we calculated from the data with a value of <span class="math inline">\(x=160\)</span> gives:</p>
<p><span class="math display">\[
\hat Y = -18.274 + 7.660 X = -18.274 + 7.660 (160) = 1207.326
\]</span> If you did some unit conversions, this turns out to be about 39 feet!</p>
<p>Further, if we wanted to draw a picture of this prediction, it would look as follows.</p>
<pre class="r"><code>plot(EstuarineCrocodiles$BodyLength ~ EstuarineCrocodiles$HeadLength,
     main=&quot;Estuarine Crocodile Measurements&quot;,
     ylab=&quot;Body Length (cm)&quot;,
     xlab=&quot;Head Length (cm)&quot;,
     col=&quot;seagreen&quot;, pch=16,
     xlim=c(0,165),
     ylim=c(0,1210))

abline(estuarine.lm)

#Predictions for Juvenile
points(87, 648, pch=16, cex=1.2, col=&quot;orange&quot;)
text(87,648, &quot;Juvenile Predicted Body Length of 648 cm&quot;, pos=2)

#Predictions for Adult
points(160, 1207, pch=16, cex=1.2, col=&quot;orange&quot;)
text(160,1207, &quot;Adult Predicted Body Length of 648 cm&quot;, pos=2)</code></pre>
<p><img src="Lesson22_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
</div>
<p><br/></p>
</div>
<p><br/> <br/></p>
</div>
</div>
<div id="case-study-manatees-and-powerboats" class="section level2">
<h2>Case Study: Manatees and Powerboats</h2>
<div style="float:right;padding:10px;">
<p><img src="Images/Manatees-ManateeBearingScarsOnBackFromBoatPropeller-RobertKBonde-USFishAndWildlifeService.png"></p>
</div>
<p><img src="Images/Step1.png"></p>
<p>Manatees are curious, peaceful sea creatures that like to sun themselves just below the ocean’s surface. Some environmentalists have claimed that manatees are being killed by powerboat propellers.</p>
<p>Is there a relationship between the number of powerboats registered in Florida and the number of manatees killed there by powerboats each year? If the powerboats are killing the manatees, then we would expect to see a relationship between the number of powerboats and the number of manatees killed by powerboats. As the number of powerboats increases, we would expect to observe a corresponding increase in manatee deaths due to powerboats.</p>
<p>We can use simple linear regression to model the relationship between the powerboat registrations and the manatee deaths. In the next lesson, we will be able to conduct a hypothesis test to determine if this relationship is statistically significant.</p>
<p><img src="Images/Step2.png"></p>
<p>The data set <a href="./Data/Manatees.xlsx">Manatees.xlsx</a> gives the number of Florida powerboat registrations (in thousands) and the number of manatees killed by powerboats for the years 1977-2006. <!--<cite>Manatees06,Manatees-ManateeData,Manatees-PowerboatData</cite>--></p>
<p><img src="Images/Step3.png"></p>
<p>As part of a regression analysis, it is important that you first create a scatterplot and visually examine the data. If the cloud of data in your scatterplot shows a curvilinear pattern, it is not appropriate to conduct simple linear regression. Procedures exist for handling curvilinear relationships. If you have a situation in your profession that involves a curvilinear relationship, you can consult a statistician or else a textbook on Linear Regression such as Kuntner, et. al., <em>Applied Linear Regression Models</em>.</p>
<p>In other words, simple linear regression is not appropriate when the graph shows a “curvilinear” shape (suggesting a nonlinear relationship). We apply simple linear regression when the two variables show a “linear” shape. If the data look like a random scattering of points, we would conclude that there is no linear relationship in the data.</p>
<table>
<colgroup>
<col width="11%" />
<col width="28%" />
<col width="31%" />
<col width="29%" />
</colgroup>
<thead>
<tr class="header">
<th>Graph</th>
<th><img src="Images/Scatter-HotDog.png"></th>
<th><img src="Images/Scatter-Hamburger.png"></th>
<th><img src="Images/Scatter-Banana.png"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Type</strong></td>
<td>Linear Pattern</td>
<td>Apparent Random Scatter</td>
<td>Nonlinear Pattern</td>
</tr>
<tr class="even">
<td><strong>Decision</strong></td>
<td>Conduct regression analysis to determine if there is a significant linear relationship</td>
<td>Linear regression is not appropriate</td>
<td>Linear regression is not appropriate</td>
</tr>
</tbody>
</table>
<div id="regression-equation" class="section level3">
<h3>Regression Equation</h3>
<p>We can use simple linear regression to develop an equation relating the number of powerboats to the number of manatees killed. Consider a model where <span class="math inline">\(Y\)</span> is the number of manatees killed and <span class="math inline">\(X\)</span> is the number of powerboats registered (in thousands).</p>
<p>If we can assume that as the number of powerboat registrations increase, the increase in the number of manatees killed will be proportional, then we can write our model in the following way: <span class="math display">\[
\hat Y = b_0 + b_1 X
\]</span> where <span class="math inline">\(\hat Y\)</span> is the predicted number of manatees killed in a year in which the number of powerboat registrations (in thousands) is given by <span class="math inline">\(X\)</span>.</p>
<p>Notice that this is the equation of a straight line. You might have written linear equations in the form <span class="math inline">\(Y=mX+b\)</span> in your algebra classes. Notice that our equation has the same form. The slope is given by <span class="math inline">\(b_1\)</span> and the <span class="math inline">\(Y\)</span>-intercept is given by <span class="math inline">\(b_0\)</span>.</p>
</div>
<div id="interpreting-the-regression-output-1" class="section level3">
<h3>Interpreting the Regression Output</h3>
<p>The output from the commands given above will include a table similar to the one shown here:</p>
<pre class="r"><code>manatee.lm &lt;- lm(Manatees$Manatees ~ Manatees$`Power Boats (in 1000&#39;s)`)
summary(manatee.lm)</code></pre>
<pre><code>
Call:
lm(formula = Manatees$Manatees ~ Manatees$`Power Boats (in 1000&#39;s)`)

Residuals:
    Min      1Q  Median      3Q     Max 
-15.758  -6.647  -1.239   4.349  22.344 

Coefficients:
                                     Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                        -42.541613   6.349634   -6.70 1.25e-07 ***
Manatees$`Power Boats (in 1000&#39;s)`   0.129162   0.008338   15.49  &lt; 2e-16 ***
---
Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1

Residual standard error: 9.239 on 33 degrees of freedom
Multiple R-squared:  0.8791,    Adjusted R-squared:  0.8754 
F-statistic:   240 on 1 and 33 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>The Y-intercept term is not multiplied by anything. This is the value of <span class="math inline">\(b_0\)</span>: <span class="math inline">\(b_0=-42.542\)</span>. The value of the slope is to be multiplied by <span class="math inline">\(X\)</span>; this is the slope of the regression equation. In our model, <span class="math inline">\(X\)</span> represents the number of powerboat registrations in Florida, in thousands. The slope for our regression equation is <span class="math inline">\(b_1=0.129\)</span>. We get the equation: <span class="math display">\[
\hat Y = -42.542 + 0.129 X
\]</span></p>
<p>We can also write the linear regression equation in the following way: <span class="math display">\[
\widehat{Manatee Deaths} = -42.542 + 0.129 \cdot Powerboats Registered
\]</span></p>
<p>The slope of the regression equation is 0.129. This means that for each one-unit increase in <span class="math inline">\(X\)</span>, we expect a corresponding increase in the average number of manatee deaths (<span class="math inline">\(Y\)</span>) of 0.129 units. Remember that the number of powerboats registered (<span class="math inline">\(X\)</span>) was given in thousands. So, a one-unit increase in <span class="math inline">\(X\)</span> implies an increase of a thousand powerboats. So, for every thousand additional powerboats registered in Florida, we expect that an additional 0.129 manatees will be killed. In other words, if there are one-hundred thousand additional powerboat registrations, we would expect to see about <span class="math inline">\(0.129 \cdot 100 = 12.9\)</span> additional manatee deaths.</p>
<p>The Y-intercept is <span class="math inline">\(-42.542\)</span>. How should we interpret this value? If there were <span class="math inline">\(X=0\)</span> thousand powerboat registrations, we would expect that approximately negative 43 (<span class="math inline">\(-43\)</span>) manatees would be killed by powerboats. This is absurd. If it does not make sense to interpret the <span class="math inline">\(Y\)</span>-intercept for these data, we simply state that it is not interpretable. The <span class="math inline">\(Y\)</span>-intercept is included in the regression equation, even though it may not be interpretable. It must be included to make the predictions more reasonable.</p>
<p>The Y-intercept is not always negative or uninterpretable. In some cases, the Y-intercept is the most important number in the equation, but often the y-intercept is not of interest to us.</p>
<p><img src="Images/Step4.png"></p>
</div>
<div id="predictions-1" class="section level3">
<h3>Predictions</h3>
<p>If we want to predict the number of manatees that will be killed if, say, 850 thousand powerboats are registered, then we enter <span class="math inline">\(X=850\)</span> into the equation we have obtained and compute the predicted value.</p>
<p><span class="math display">\[
\hat Y = -42.542 + 0.129 (850) = 67.108
\]</span> Note that if there are 850 thousand powerboats registered, then the regression equation suggests that there will be an estimated 67 manatees killed.</p>
</div>
<div id="drawing-the-regression-line-on-a-scatterplot" class="section level3">
<h3>Drawing the Regression Line on a Scatterplot</h3>
<p>The following plot shows the regression line on the scatterplot.</p>
<pre class="r"><code>plot(Manatees$Manatees ~ Manatees$`Power Boats (in 1000&#39;s)`,
     main=&quot;Manatee Deaths in Florida, 1977-2006&quot;,
     xlab=&quot;Number of Registered Power Boats that Year&quot;,
     ylab=&quot;Number of Manatees that Died that Year&quot;,
     col=&quot;darkgray&quot;)

abline(manatee.lm)</code></pre>
<p><img src="Lesson22_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<p>You will observe that the points are not as tightly clustered around the regression line for the manatee data, compared to the crocodile data, but that there is still a fairly strong correlation in the data of <span class="math inline">\(0.9376\)</span>.</p>
<pre class="r"><code>cor(Manatees$`Power Boats (in 1000&#39;s)`, Manatees$Manatees)</code></pre>
<pre><code>[1] 0.9376087</code></pre>
<p><br></p>
<p><img src="Images/Step5.png"></p>
<p>Knowledge of how the manatee deaths are so strongly related to the number of registered power boats should invite discussion on what action should be taken, but does not specifically tell us the action to take. Actions that have been taken in response to this data include idle speed zones, slow speed zones, motorboats prohibited zones, and no entry zones. (<a href="https://myfwc.com/media/25256/guidelinesprotectingmanatees.pdf">See here</a> for details if you are interested.)</p>
</div>
</div>
<div id="introduction-to-multiple-regression" class="section level2">
<h2>Introduction to Multiple Regression</h2>
<p>Sometimes it is necessary to use more than one predictor (independent) variable to predict the value of a response (dependent) variable. For example, if we want to predict the stopping distance for a car on dry roads, we might want to use (<span class="math inline">\(i\)</span>) the initial speed of the car, (<span class="math inline">\(ii\)</span>) the weight of the car, and (<span class="math inline">\(iii\)</span>) the amount of tread on the tires to predict the distance required to stop the car.</p>
<p>Although it is fairly straightforward to create a model and get the estimated multiple regression equation, the interpretation of the results can be a little tricky. If you need to conduct multiple regression (that is, regression with several predictor variables) you may want to study the topic in depth or hire a statistician. <!--
Most statistical packages (including SPSS) will easily handle multiple regression analyses.  Unfortunately, in many cases Excel provides incorrect results for multiple regression.  Microsoft seems to have been aware of the issues for decades, but the problem has not been corrected.  Using Excel to conduct multiple regression analyses is strongly discouraged.
--></p>
<p><br></p>
</div>
<div id="whats-in-a-name" class="section level2">
<h2>What’s in a Name?</h2>
<p>When we want to refer to simple linear regression, there are a variety of names that could be used: simple linear regression, ordinary least-squares regression, linear regression, regression, or (most ostentatiously) simple ordinary linear least squares regression.</p>
<p>If we need to distinguish between simple linear regression and multiple regression, the key will be whether we use the word “multiple.” If we are discussing regression, and the word “multiple” is not used, then assume we are talking about simple least squares regression. <!--

## Historical Notes
### Why is error called error?
### Why is regression called regression?

TextGoesHere

--></p>
<p><br></p>
</div>
<div id="summary" class="section level2">
<h2>Summary</h2>
<div class="SummaryHeading">
Remember…
</div>
<div class="Summary">
<ul>
<li><p>In statistics, we write the <strong>linear regression equation</strong> as <span class="math inline">\(\hat Y=b_0+b_1X\)</span> where <span class="math inline">\(b_0\)</span> is the <strong>Y-intercept</strong> of the line and <span class="math inline">\(b_1\)</span> is the <strong>slope</strong> of the line.</p></li>
<li><p>To calculate the values of <span class="math inline">\(b_0\)</span> and <span class="math inline">\(b_1\)</span> in R use the <code>lm( )</code> function and the <code>summary( )</code> function as <a href="Lesson22.html#r-instructions-for-performing-a-linear-regression">shown here</a>.</p></li>
<li><p>To add the regression line to a scatterplot, use the <code>abline( )</code> function as <a href="Lesson22.html#r-instructions-for-graphing-the-regression-line">shown here</a>.</p></li>
<li><p>Linear regression allows us to predict values of <span class="math inline">\(Y\)</span> for a given <span class="math inline">\(X\)</span>. This is done by first calculating the coefficients <span class="math inline">\(b_0\)</span> and <span class="math inline">\(b_1\)</span> and then plugging in the desired value of <span class="math inline">\(X\)</span> and solving for <span class="math inline">\(Y\)</span>.</p></li>
<li><p>The <strong>independent (or explanatory) variable (<span class="math inline">\(X\)</span>)</strong> is the variable which is <em>not</em> affected by what happens to the other variable. The <strong>dependent (or response) variable (<span class="math inline">\(Y\)</span>)</strong> is the variable which <em>is</em> affected by what happens to the other variable. For example, in the correlation between number of powerboats and number of manatee deaths, the number of deaths is affected by the number of powerboats in the water, but not the other way around. So, we would assign <span class="math inline">\(X\)</span> to represent the number of powerboats and <span class="math inline">\(Y\)</span> to represent the number of manatee deaths.</p></li>
<li><p>The y-intercept <span class="math inline">\(b_0\)</span> is interpreted as the mean y-value for when the x-value equals zero.</p></li>
<li><p>The slope <span class="math inline">\(b_1\)</span> is interpreted as the change in the mean y-value for each one unit change in the x-value.</p></li>
</ul>
<p><br></p>
</div>
<p><br></p>
</div>
<div id="navigation" class="section level2">
<h2>Navigation</h2>
<center>
<table>
<colgroup>
<col width="38%" />
<col width="30%" />
<col width="30%" />
</colgroup>
<thead>
<tr class="header">
<th align="center"><strong>Previous Reading</strong></th>
<th align="center"><strong>This Reading</strong></th>
<th align="center"><strong>Next Reading</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"><a href="Lesson21.html">Lesson 21: <br> Describing Bivariate Data: Scatterplots, Correlation, &amp; Covariance</a></td>
<td align="center">Lesson 22: <br> Simple Linear Regression</td>
<td align="center"><a href="Lesson23.html">Lesson 23: <br> Inference for Bivariate Data)</a></td>
</tr>
</tbody>
</table>
</center>
</div>

<br />
<hr />
<p>Copyright &copy; 2020 Brigham Young University-Idaho. All rights reserved.</p>



</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
