<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Lesson 14: Inference using ANOVA (Several Independent Samples)</title>

<script src="site_libs/header-attrs-2.16/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cerulean.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>






<link rel="stylesheet" href="styles.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Math 221</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Unit 1
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="Lesson01_Campus.html">Lesson 1: (On Campus) Course Intro &amp; Probability</a>
    </li>
    <li>
      <a href="Lesson01.html">Lesson 1: (Online) Course Intro &amp; Probability</a>
    </li>
    <li>
      <a href="Lesson02.html">Lesson 2: The Statistical Process</a>
    </li>
    <li>
      <a href="Lesson03.html">Lesson 3: Describing Quantitative Data (Shape &amp; Center)</a>
    </li>
    <li>
      <a href="Lesson04.html">Lesson 4: Describing Quantitative Data (Spread)</a>
    </li>
    <li>
      <a href="Lesson05.html">Lesson 5: Normal Distributions</a>
    </li>
    <li>
      <a href="Lesson06.html">Lesson 6: The Central Limit Theorem</a>
    </li>
    <li>
      <a href="Lesson07.html">Lesson 7: Calculating Probabilities involving the Sample Mean</a>
    </li>
    <li>
      <a href="Lesson08.html">Lesson 8: Unit 1 Review</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Unit 2
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="Lesson09.html">Lesson 9: Hypothesis Test for One Mean (Sigma Known)</a>
    </li>
    <li>
      <a href="Lesson10.html">Lesson 10: Confidence Interval for One Mean (Sigma Known)</a>
    </li>
    <li>
      <a href="Lesson11.html">Lesson 11: Inference for One Mean (Sigma Unknown)</a>
    </li>
    <li>
      <a href="Lesson12.html">Lesson 12: Inference for Match Pairs</a>
    </li>
    <li>
      <a href="Lesson13.html">Lesson 13: Inference for Two Independent Samples</a>
    </li>
    <li>
      <a href="Lesson14.html">Lesson 14: Inference for Several Independent Samples</a>
    </li>
    <li>
      <a href="Lesson15.html">Lesson 15: Unit 2 Review</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Unit 3
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="Lesson16.html">Lesson 16: Describing Categorical Data</a>
    </li>
    <li>
      <a href="Lesson17.html">Lesson 17: Inference for One Proportion</a>
    </li>
    <li>
      <a href="Lesson18.html">Lesson 18: Inference for Two Proportions</a>
    </li>
    <li>
      <a href="Lesson19.html">Lesson 19: Inference for Independence of Categorical Data</a>
    </li>
    <li>
      <a href="Lesson20.html">Lesson 20: Unit 3 Review</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Unit 4
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="Lesson21.html">Lesson 21: Describing Bivariate Data</a>
    </li>
    <li>
      <a href="Lesson22.html">Lesson 22: Simple Linear Regression</a>
    </li>
    <li>
      <a href="Lesson23.html">Lesson 23: Inference for Bivariate Data</a>
    </li>
    <li>
      <a href="Lesson24.html">Lesson 24: Unit 4 Review</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="RHelp.html">R Help</a>
</li>
<li>
  <a href="Data.html">Data</a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Lesson 14: Inference using ANOVA (Several
Independent Samples)</h1>

</div>

<div id="TOC">
<ul>
<li><a href="#lesson-outcomes" id="toc-lesson-outcomes">Lesson
Outcomes</a></li>
<li><a href="#case-study-the-effects-of-gratitude"
id="toc-case-study-the-effects-of-gratitude">Case Study: The Effects of
Gratitude</a></li>
<li><a href="#analysis-of-variance-anova"
id="toc-analysis-of-variance-anova">Analysis of Variance (ANOVA)</a>
<ul>
<li><a
href="#r-instructions-for-numerical-summaries-of-several-groups-long-data"
id="toc-r-instructions-for-numerical-summaries-of-several-groups-long-data">R
Instructions for Numerical Summaries of Several Groups (Long
Data)</a></li>
<li><a
href="#r-instructions-for-side-by-side-boxplots-of-several-groups-long-data"
id="toc-r-instructions-for-side-by-side-boxplots-of-several-groups-long-data">R
Instructions for Side-by-Side Boxplots of Several Groups (Long
Data)</a></li>
<li><a href="#r-instructions-for-conducting-an-anova-test-long-data"
id="toc-r-instructions-for-conducting-an-anova-test-long-data">R
Instructions for Conducting an ANOVA Test (Long Data)</a></li>
<li><a href="#the-f-distribution" id="toc-the-f-distribution">The <span
class="math inline">\(F\)</span>-distribution</a></li>
<li><a href="#requirements-of-anova"
id="toc-requirements-of-anova">Requirements of ANOVA</a></li>
</ul></li>
<li><a href="#anova-with-wide-data-soccer-shoes"
id="toc-anova-with-wide-data-soccer-shoes">ANOVA with Wide Data: Soccer
Shoes</a>
<ul>
<li><a href="#r-instructions-for-converting-wide-data-to-long-format"
id="toc-r-instructions-for-converting-wide-data-to-long-format">R
Instructions for Converting “Wide” Data to “Long” Format</a></li>
</ul></li>
<li><a href="#summary" id="toc-summary">Summary</a></li>
<li><a href="#navigation" id="toc-navigation">Navigation</a></li>
</ul>
</div>

<script type = "text/javascript">
 function showhide(id) {
    var e = document.getElementById(id);
    e.style.display = (e.style.display == 'block') ? 'none' : 'block';
 }
</script>
<!--
<div style = "float:right;width = 40%;">
<br/>
<div style = "padding-left:10%;">**Optional Lesson Video**</div>
<iframe width = "90%" align = "right" src = "https://www.youtube.com/embed/videoseries?list = PLaZryQtbPQC8BeDBR9mQR2d8nnqK_iQ0j" frameborder = "1" allow = "autoplay; encrypted-media" allowfullscreen></iframe>
</div>
-->
<div id="lesson-outcomes" class="section level2">
<h2>Lesson Outcomes</h2>
<a href = "javascript:showhide('oc')"><span
style="font-size:8pt;">Show/Hide Outcomes</span></a>
<div id="oc" style="display:none;">
<p>By the end of this lesson, you should be able to do the following for
a hypothesis test for several means (ANOVA):</p>
<ul>
<li>Perform a hypothesis test for ANOVA (several independent samples)
using the following steps:
<ul>
<li>State the null and alternative hypotheses</li>
<li>State the level of significance (α)</li>
<li>Create numerical and graphical summaries of the data</li>
<li>Calculate the test-statistic, degrees of freedom and P-value of the
test using software</li>
<li>Assess statistical significance by comparing the P-value to the
level of significance (α)</li>
<li>State the appropriate conclusion for the hypothesis test</li>
<li>Check the requirements for the hypothesis test</li>
</ul></li>
</ul>
</div>
<p><br></p>
<div style="clear:both;">

</div>
<p><br/></p>
<p><img src = "Images/StepsAll.png"></p>
</div>
<div id="case-study-the-effects-of-gratitude" class="section level2">
<h2>Case Study: The Effects of Gratitude</h2>
<br>
<table>
<tbody>
<tr class="odd">
<!-- <td><p><img src = "Images/GordonBHinckley.png"></p></td> -->
<td>
<p>
<img src = "Images/gordon_b_hinckley_small.png">
</p>
</td>
<td>
<p>
<span class="math inline">\(~ ~\)</span>
</p>
</td>
<td>
<p>
President Gordon B. Hinckley said, "My plea is that we stop seeking out
the storms and enjoy more fully the sunlight. I am suggesting that as we
go through life, we ‘accentuate the positive.’ I am asking that we look
a little deeper for the good, that we still our voices of insult and
sarcasm, that we more generously compliment and endorse virtue and
effort" (<em>Standing for Something</em>, 2000, p.101).
</p>
</td>
</tr>
<tr class="even">
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
<p><img src = "Images/Step1.png"></p>
<div style="float:right; padding:10px;">
<p><img src = "Images/Midnight_sun.jpg"></p>
</div>
<p><strong>Summarize the relevant background information</strong></p>
<p>Robert Emmons and Michael McCullough investigated the effects of
gratitude on people’s perception of life as a
whole<!--<cite>Emmons03</cite>-->. In a study of <span
class="math inline">\(n = 192\)</span> undergraduates, the people were
randomly assigned to one of three groups.</p>
<ul>
<li>Group 1 (Gratitude): The participants in this group were asked to
record five things each week for which they were grateful or
thankful.</li>
<li>Group 2 (Hassles): The volunteers in this group recorded five
irritants that had occurred to them in the previous week.</li>
<li>Group 3 (Events): The people in the events group recorded five
things that occurred in the past week that had an impact on them.</li>
</ul>
<p>In addition to the weekly record of the five things they recorded
their level of satisfaction with life in general. (Higher values are
more favorable.) Reports were collected for nine weeks, and the overall
level of satisfaction with life as a whole was recorded for each
individual. The researchers wanted to determine if there was a
difference in the perception of life as a whole between the subjects
assigned to each of the three groups. Stated differently, they wanted to
determine if expressing gratitude affects a person’s view of life in
general.</p>
<p>Here is an excerpt of data representing the results of this
study:</p>
<table>
<thead>
<tr class="header">
<th align="center">Person</th>
<th align="center">Treatment Group</th>
<th align="center">Happiness Score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">1</td>
<td align="center">Grateful</td>
<td align="center">6.1</td>
</tr>
<tr class="even">
<td align="center">2</td>
<td align="center">Grateful</td>
<td align="center">6.2</td>
</tr>
<tr class="odd">
<td align="center"><span class="math inline">\(\vdots\)</span></td>
<td align="center"><span class="math inline">\(\vdots\)</span></td>
<td align="center"><span class="math inline">\(\vdots\)</span></td>
</tr>
<tr class="even">
<td align="center">64</td>
<td align="center">Grateful</td>
<td align="center">4.9</td>
</tr>
<tr class="odd">
<td align="center">65</td>
<td align="center">Hassles</td>
<td align="center">5.9</td>
</tr>
<tr class="even">
<td align="center"><span class="math inline">\(\vdots\)</span></td>
<td align="center"><span class="math inline">\(\vdots\)</span></td>
<td align="center"><span class="math inline">\(\vdots\)</span></td>
</tr>
<tr class="odd">
<td align="center">127</td>
<td align="center">Hassles</td>
<td align="center">3.8</td>
</tr>
<tr class="even">
<td align="center">128</td>
<td align="center">Events</td>
<td align="center">4.9</td>
</tr>
<tr class="odd">
<td align="center"><span class="math inline">\(\vdots\)</span></td>
<td align="center"><span class="math inline">\(\vdots\)</span></td>
<td align="center"><span class="math inline">\(\vdots\)</span></td>
</tr>
<tr class="even">
<td align="center">192</td>
<td align="center">Events</td>
<td align="center">3.7</td>
</tr>
</tbody>
</table>
<p>Higher values indicate a greater level of satisfaction with life as a
whole.</p>
<p>How might we analyze these data? One possible method would be to
conduct separate t-tests for all the possible pairs of groups in the
study. If we did this, we would need to conduct a separate t-test to
compare groups 1 &amp; 2, 1 &amp; 3 and 2 &amp; 3. If the probability of
committing a Type I error is <span class="math inline">\(\alpha =
.05\)</span> on each of these tests, then the probability that we would
commit a Type I error on at least one of the tests is much greater than
0.05. We need a hypothesis test that we can use to compare all the
groups at once. The procedure that allows us to do this is called
Analysis of Variance (ANOVA).</p>
</div>
<div id="analysis-of-variance-anova" class="section level2">
<h2>Analysis of Variance (ANOVA)</h2>
<p>ANOVA, an acronym for <strong>An</strong>alysis <strong>o</strong>f
<strong>Va</strong>riance, is a test for equality of several means. It
allows us to compare the means for several groups in a single hypothesis
test. It is based on a comparison of the spread (or variance) of the
data <em>within</em> each of the groups compared to the spread (or
variance) <em>between</em> the means of the groups.</p>
<p>In an ANOVA test, the null hypothesis is typically expressed in
words: <span class="math display">\[H_0: \text{All the population means
are equal.}\]</span> The alternative hypothesis is also stated in words
as: <span class="math display">\[H_a: \text{One or more of the
population means differs from the others.}\]</span></p>
<p>If the sample means differ from each other enough, then we conclude
that the true population means for each group are not all equal. If the
sample means do not differ by much (when compared to the spread of the
data in each group) then we fail to reject the null hypothesis that all
the populations means are equal.</p>
<p>We will use the level of significance, <span
class="math inline">\(\alpha\)</span>, and the <span
class="math inline">\(P\)</span>-value just as we have in the other
hypothesis tests.</p>
<p><strong>State the null and alternative hypotheses and the level of
significance</strong> <span class="math display">\[
\begin{align}
H_0: &amp; ~ \textrm{The population mean happiness scores are equal for
each treatment} \\
H_a: &amp; ~ \textrm{At least one of treatments has a different
population mean happiness score}
\end{align}
\]</span></p>
<p>We will use the <span class="math inline">\(\alpha = 0.05\)</span>
level of significance.</p>
<p><img src = "Images/Step2.png"></p>
<p><strong>Describe the data collection procedures</strong></p>
<p>The 192 students that volunteered to participate in the study were
randomly assigned to one of the three treatment groups: Events, Hassles,
or Gratitude. They wrote in a weekly journal, according to their group
assignment. At the end of the semester, they completed a questionnaire
that asked about their attitude toward life. The responses on the survey
were coded into a number, where higher numbers represent a more positive
outlook on life.</p>
<p><img src = "Images/Step3.png"></p>
<p><strong>Give the relevant summary statistics</strong></p>
<div
id="r-instructions-for-numerical-summaries-of-several-groups-long-data"
class="section level3">
<h3>R Instructions for Numerical Summaries of Several Groups (Long
Data)</h3>
<div class="SoftwareHeading">
R Instructions
</div>
<div class="Software">
<p><strong>To compute numerical summaries for several
groups:</strong></p>
<ul>
<li><p>Load the data: <code>gratitude</code>. Download these data from
<a href="https://byuistats.github.io/M221R/data/gratitude.xlsx"
class="uri">https://byuistats.github.io/M221R/data/gratitude.xlsx</a>.
You can <a
href="https://byuistats.github.io/M221R/RHelp.html#Reading_in_Data">click
here</a> for instructions on how to import the dataset into R.</p></li>
<li><p>Load <code>library(mosaic)</code>.</p></li>
<li><p>Use the <code>favstats(...)</code> function with the quantitative
data column name listed first, followed by a tilde, <code>~</code>,
which is followed by the categorical data column name. We indicate that
these columns are part of the <code>gratitude</code> data frame using
the command <code>data = gratitude</code>.</p></li>
</ul>
<pre class="r"><code>library(mosaic) 
favstats(happiness ~ treatment, data = gratitude)</code></pre>
<pre><code>  treatment min    Q1 median    Q3 max     mean        sd  n missing
1    Events 3.0 4.100   4.70 5.100 6.8 4.660000 0.8483071 65       0
2  Grateful 3.5 4.275   5.05 5.625 7.5 5.050000 0.9443231 64       0
3   Hassles 3.3 3.850   4.60 5.400 6.2 4.674603 0.8320143 63       0</code></pre>
<p><br></p>
</div>
<p><br></p>
</div>
<div
id="r-instructions-for-side-by-side-boxplots-of-several-groups-long-data"
class="section level3">
<h3>R Instructions for Side-by-Side Boxplots of Several Groups (Long
Data)</h3>
<div class="SoftwareHeading">
R Instructions
</div>
<div class="Software">
<p><strong>To make an appropriate graph to illustrate the
data:</strong></p>
<ul>
<li>Use the <code>boxplot(...)</code> function with the quantitative
data listed first, followed by a <code>~</code>, followed by the
categorical data.</li>
<li>Specify colors using either <code>col = "steelblue3"</code> to give
all boxes the same color, or use
<code>col = c("brown3","steelblue3","tan3")</code> to give each box a
different color. Of course, use any color names you like.</li>
<li>Specify axes labeling with <code>main = "A main title"</code>,
<code>xlab = "An x-axis label"</code>, and
<code>ylab = "A y-axis label"</code>.</li>
</ul>
<pre class="r"><code>boxplot(gratitude$happiness ~ gratitude$treatment,
        col = c(&quot;brown3&quot;,&quot;steelblue3&quot;,&quot;tan3&quot;),
        main = &quot;The Effects of Gratitude&quot;,
        xlab = &quot;Treatment Groups&quot;,
        ylab = &quot;Happiness Score (Higher is More Positive)&quot;)</code></pre>
<p><img src="Lesson14_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p><br></p>
</div>
<p><br></p>
<p>Based on the numerical summaries and boxplot, the gratitude group had
a higher life happiness mean score of 5.05 compared to the other two
groups of 4.66 (Events group) and 4.67 (Hassles group). This suggests
that perhaps exercising a daily recognition of things one is grateful
for can result in greater life satisfaction. However, it is important to
first <strong>make inference</strong> before we decide if the data
really warrants this conclusion.</p>
<p><img src = "Images/Step4.png"></p>
<p><strong>Make Inference</strong></p>
</div>
<div id="r-instructions-for-conducting-an-anova-test-long-data"
class="section level3">
<h3>R Instructions for Conducting an ANOVA Test (Long Data)</h3>
<div class="SoftwareHeading">
R Instructions
</div>
<div class="Software">
<p>To conduct a test for several means (ANOVA) in R, do the
following:</p>
<ul>
<li>Load the <code>gratitude</code> data if you haven’t already,</li>
<li>Use the <code>aov(...)</code> function and the assignment operator
<code>&lt;-</code> to perform and save the results of the test to any
name you want to create for the test. Here we use the name
<code>aov_output</code>.</li>
<li>When using the <code>aov(...)</code> function, place the
quantitative variable first, followed by a <code>~</code>, followed by
the categorical variable. As in other examples, we indicate the data
frame using the <code>data =</code> argument.</li>
<li>Use the <code>summary(...)</code> function to view the results of
the ANOVA test in a nice format.</li>
</ul>
<pre class="r"><code>aov_output &lt;- aov(happiness ~ treatment, data = gratitude)
summary(aov_output)</code></pre>
<pre><code>             Df Sum Sq Mean Sq F value Pr(&gt;F)  
treatment     2   6.26   3.130   4.075 0.0185 *
Residuals   189 145.16   0.768                 
---
Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>In the ANOVA table output summary, you will find</p>
<ul>
<li>the test statistic (<span class="math inline">\(F\)</span>, see
<strong>The <span class="math inline">\(F\)</span>-Distribution</strong>
section below for an explanation),</li>
<li>the <span class="math inline">\(P\)</span>-value (Pr(&gt;F)),</li>
<li>and the two separate degrees of freedoms (Df) for the <span
class="math inline">\(F\)</span> statistic.</li>
</ul>
<p>Note that there are two numbers specifying the degrees of freedom.
These are given as the “Treatment Group” and “Residuals” degrees of
freedom, respectively. The degrees of freedom for the “Treatment Group”
are one less than the number of groups, in this case there are three
groups (Events, Hassles, and Grateful) so there are 2 degrees of
freedom. The “Residuals” degrees of freedom is equal to the total sample
size (<span class="math inline">\(n = 192\)</span> in this study) minus
1, then minus the Df for the “Treatment Group”, which is 2 in this case.
That leaves us with <span class="math inline">\(192 - 1 - 2 =
189\)</span> “residual” degrees of freedom (or leftover degrees of
freedom).</p>
<p>More advanced statistics courses will go deeper into explaining these
degrees of freedom and why they matter. For now, just recognize that the
“Df” values are used to obtain the “Mean Sq” values by dividing the “Sum
Sq” values by the “Df” values. Then, the “F value” is obtained by
dividing the two “Mean Sq” values. These “Mean Sq” values are
essentially <em>variances</em> and thus the name of the method is called
“Analaysis of Variance” or ANOVA because the F-statistic is the ratio of
two variances. When the F-statistic is large, that tells us that the
means are farther apart than we would expect if all samples were from
the same population of data.</p>
</div>
<p><br/></p>
</div>
<div id="the-f-distribution" class="section level3">
<h3>The <span class="math inline">\(F\)</span>-distribution</h3>
<p><img src = "Images/Gratitude-F.png"> The test statistic in ANOVA
follows an <span class="math inline">\(F\)</span>-distribution. This is
the first time we have encountered this distribution. In previous tests,
we have used the test statistics <span class="math inline">\(z\)</span>
and <span class="math inline">\(t\)</span>. For the ANOVA test, we use
the <span class="math inline">\(F\)</span>-statistic.</p>
<p>Here is a brief summary of the characteristics of the <span
class="math inline">\(F\)</span>-distribution:</p>
<ul>
<li>It is right skewed.</li>
<li>The values of <span class="math inline">\(F\)</span> are never
negative.</li>
<li>The <span class="math inline">\(P\)</span>-value for the ANOVA test
is the area in the <em>right tail</em>. We will never divide the area in
the tail.</li>
</ul>
</div>
<div id="requirements-of-anova" class="section level3">
<h3>Requirements of ANOVA</h3>
<p><strong>Verify the requirements have been met.</strong></p>
<p>There are two requirements of ANOVA that we can verify directly:</p>
<!-- 
- The data represent a simple random sample.

    We cannot check this requirement by looking at the data. As long as the data are representative of the population, the intent of this requirement is satisfied. 
-->
<ul>
<li><p>The data are normally distributed in each group.</p>
<p>We can check this by looking at the boxplots we created previously.
If each boxplot is relatively symmetric and there are no major outliers,
it is reasonable to conclude that the data are sufficiently normal to
proceed with the analysis. We can take this approach because ANOVA is
robust to violations of requirements. In other words, results from ANOVA
tests are reasonably good even if there are mild to moderate violations
of the requirements.</p>
<p>In looking at the boxplot of the gratitude data above, we see the
median is in the center of each box (it isn’t pressed up against either
end of the box) and that the whiskers of each box go out somewhat
equally to either side of the box. While there are a couple of outliers
in the Events group, and the top whisker for the “Grateful” group is
longer than its bottom whisker, this would be considered a very
“normally distributed” set of boxplots.</p></li>
<li><p>The variances are equal for each group.</p>
<p>This requirement is checked by examining the variances. Remember, the
variance is the square of the standard deviation. The rule we will use
is: <em>if the largest variance is more than four times as big as the
smallest variance, we will conclude that the variances are
equal.</em></p>
<p>We can find the variance using the following R command:</p></li>
</ul>
<pre class="r"><code>var(happiness ~ treatment, data = gratitude)</code></pre>
<pre><code>##    Events  Grateful   Hassles 
## 0.7196250 0.8917460 0.6922478</code></pre>
<pre><code>For the gratitude study, the variances of the Events, Grateful, and Hassles groups were 0.720, 0.892, and 0.692, respectively. The largest of these variances is 0.892 and the smallest is 0.692. Notice that the largest variance is not more than four times as big as the smallest variance. So, we conclude the assumption is satisfied.</code></pre>
<br>
<div class="message Tip">
The variance is the square of the standard deviation. The sample
variance is denoted by the symbol <span
class="math inline">\(s^2\)</span>.
</div>
<p><br> <br></p>
<p><strong>Give the test statistic and its value</strong></p>
<p>This can be found in the output. Our test statistic, <span
class="math inline">\(F\)</span>, is: <span class="math display">\[F =
4.075\]</span></p>
<p><strong>State the degrees of freedom</strong></p>
<p>There are 2 and 189 degrees of freedom.</p>
<p>The order in which these are stated is important. For an F-test, it
is not the same to have 2 and 189 degrees of freedom as it is to have
189 and 2 degrees of freedom.</p>
<p><strong>Mark the test statistic and <span
class="math inline">\(P\)</span>-value on a graph of the sampling
distribution</strong></p>
<p>While this is not something that you have to do in this course, it is
good to remember that the <span class="math inline">\(P\)</span>-value
provided to you in the output of the ANOVA test in R is the “probability
of obtaining a test statistic as extreme or more extreme than the one
observed, assuming the null hypothesis is true.” That is why the
notation for it in the summary output is <code>Pr(&gt;F)</code>. If we
drew a picture of the F-distribution we would see that it starts at
zero, is strongly right-skewed, and goes to infinity. Marking the
observed test statistic on the graph and shading the area to the right
would give the p-value.</p>
<p><img src = "Images/Gratitude-F.png"></p>
<p><strong>Find the <span class="math inline">\(P\)</span>-value and
compare it to the level of significance</strong></p>
<p>The <span class="math inline">\(P\)</span>-value of the ANOVA test
can be found in the output summary of the test. <span
class="math display">\[P\textrm{-value} = 0.019 &lt; 0.05 =
\alpha\]</span></p>
<p><strong>State your decision</strong></p>
<p>Since <span class="math inline">\(P\)</span>-value$ = 0.019 &lt; 0.05
= $, we reject the null hypothesis.</p>
<p><img src = "Images/Step5.png"></p>
<p><strong>Present your conclusion in an English sentence, relating the
result to the context of the problem</strong></p>
<p>There is sufficient evidence to suggest that at least one of the
three groups has a mean level of satisfaction with life that differs
from the others. In short, the mean level of satisfaction with life in
general is not the same for all three groups.</p>
<p>If we take a closer look, we see that the Hassles and Events groups
had means that were fairly close together. However, the Grateful group
appears to have a significantly higher mean level of satisfaction than
the other two groups.</p>
</div>
</div>
<div id="anova-with-wide-data-soccer-shoes" class="section level2">
<h2>ANOVA with Wide Data: Soccer Shoes</h2>
<p><span id="id_21:soccer_shoesExplanation"></span></p>
<p><img src = "Images/StepsAll.png"></p>
<p><img src = "Images/Step1.png"></p>
<p><strong>Summarize the relevant background information</strong></p>
<p>Nike, a company that makes sporting goods including shoes, funded a
study to compare five soccer shoe designs.
<!--<cite>Hennig09,Hennig10</cite>--> The objective of the research was
to determine if there is a difference in the mean accuracy soccer
players achieve using different Nike shoe designs.</p>
<p>Data representing the results of this study are given in the data
frame <code>soccer_shoes</code>. Download these data from <a
href="https://byuistats.github.io/M221R/data/soccer_shoes.xlsx"
class="uri">https://byuistats.github.io/M221R/data/soccer_shoes.xlsx</a>.
You can <a
href="https://byuistats.github.io/M221R/RHelp.html#Reading_in_Data">click
here</a> for instructions on how to import the dataset into R.</p>
<div id="r-instructions-for-converting-wide-data-to-long-format"
class="section level3">
<h3>R Instructions for Converting “Wide” Data to “Long” Format</h3>
<p>After reading in the data, examine the format in which they are
presented.</p>
<p>Here are the first eight rows:</p>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:center;">
shoe_a
</th>
<th style="text-align:center;">
shoe_b
</th>
<th style="text-align:center;">
shoe_c
</th>
<th style="text-align:center;">
shoe_d
</th>
<th style="text-align:center;">
shoe_e
</th>
<th style="text-align:center;">
socks
</th>
<th style="text-align:left;">
comments
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
35
</td>
<td style="text-align:center;">
30
</td>
<td style="text-align:center;">
25
</td>
<td style="text-align:center;">
26
</td>
<td style="text-align:center;">
43
</td>
<td style="text-align:center;">
34
</td>
<td style="text-align:left;">
These data are based on Figure 5 in the article:
</td>
</tr>
<tr>
<td style="text-align:center;">
32
</td>
<td style="text-align:center;">
27
</td>
<td style="text-align:center;">
40
</td>
<td style="text-align:center;">
19
</td>
<td style="text-align:center;">
30
</td>
<td style="text-align:center;">
37
</td>
<td style="text-align:left;">
The influence of soccer shoe design on playing performance: a series of
</td>
</tr>
<tr>
<td style="text-align:center;">
39
</td>
<td style="text-align:center;">
27
</td>
<td style="text-align:center;">
35
</td>
<td style="text-align:center;">
32
</td>
<td style="text-align:center;">
38
</td>
<td style="text-align:center;">
46
</td>
<td style="text-align:left;">
biomechanical studies
</td>
</tr>
<tr>
<td style="text-align:center;">
44
</td>
<td style="text-align:center;">
38
</td>
<td style="text-align:center;">
30
</td>
<td style="text-align:center;">
37
</td>
<td style="text-align:center;">
36
</td>
<td style="text-align:center;">
39
</td>
<td style="text-align:left;">
Ewald M. Hennig and Thorsten Sterzing
</td>
</tr>
<tr>
<td style="text-align:center;">
35
</td>
<td style="text-align:center;">
36
</td>
<td style="text-align:center;">
23
</td>
<td style="text-align:center;">
29
</td>
<td style="text-align:center;">
27
</td>
<td style="text-align:center;">
27
</td>
<td style="text-align:left;">
NA
</td>
</tr>
<tr>
<td style="text-align:center;">
27
</td>
<td style="text-align:center;">
31
</td>
<td style="text-align:center;">
24
</td>
<td style="text-align:center;">
43
</td>
<td style="text-align:center;">
30
</td>
<td style="text-align:center;">
37
</td>
<td style="text-align:left;">
Hennig, Ewald M. and Sterzing, Thorsten(2010) ’The influence of soccer
shoe design on playing
</td>
</tr>
<tr>
<td style="text-align:center;">
28
</td>
<td style="text-align:center;">
36
</td>
<td style="text-align:center;">
31
</td>
<td style="text-align:center;">
38
</td>
<td style="text-align:center;">
34
</td>
<td style="text-align:center;">
41
</td>
<td style="text-align:left;">
performance: a series of biomechanical studies’, Footwear Science, 2: 1,
3 — 11
</td>
</tr>
<tr>
<td style="text-align:center;">
31
</td>
<td style="text-align:center;">
36
</td>
<td style="text-align:center;">
28
</td>
<td style="text-align:center;">
30
</td>
<td style="text-align:center;">
25
</td>
<td style="text-align:center;">
37
</td>
<td style="text-align:left;">
NA
</td>
</tr>
</tbody>
</table>
<p>There are six columns of data, where each column gives the accuracy
rating for a different type of footwear. Note that this is wide data,
since every column gives the data for one group. The last column
provides the reference for the articles from which the data were
derived.</p>
<p>In order to conduct an ANOVA analysis to determine if the mean
accuracy is the same for the six types of footwear, we need to convert
the data into “long” format. We will do this in three steps:</p>
<ol style="list-style-type: decimal">
<li><p>Examine the data. We can either do this with either the
<code>View(soccer_shoes)</code> or <code>head(soccer_shoes)</code>
commands.</p></li>
<li><p>We will “stack” the data to create a new data frame in long
format. We filter out any columns that are not numeric in this process.
The column titled <code>comments</code> is deleted before the data are
stacked. We give this new data frame a separate name:
<code>soccer</code>. Notice that <code>soccer</code> that is in “long”
format, where <code>soccer_shoes</code> is in “wide” format.</p></li>
</ol>
<pre class="r"><code>  soccer &lt;- stack(Filter(is.numeric, soccer_shoes))</code></pre>
<p>Use <code>View(soccer)</code> to explore these data. Notice that R
has transformed the data, so that it is now in “long” format, where the
accuracy values are in a column called <code>values</code> and the label
indicating (“ind”) the type of footwear is in a second column called
<code>ind</code>.</p>
<p>After making this change, the techniques for performing ANOVA on long
data can be applied to the data set <code>soccer</code>.</p>
<p><strong>State the null and alternative hypotheses and the level of
significance</strong> <span class="math display">\[
\begin{align}
H_0: &amp; \textrm{All the means are equal} \\
H_a: &amp; \textrm{At least one of the means differs}
\end{align}
\]</span></p>
<p>We will use the <span class="math inline">\(\alpha = 0.10\)</span>
level of significance.</p>
<p><img src = "Images/Step2.png"></p>
<p><strong>Describe the data collection procedures</strong></p>
<p>As part of the research, they asked trained soccer players to kick a
ball at a target. The target was placed 115 cm above the ground and at a
distance of 10 m from the players. Using electronic equipment, the
researchers recorded the distance from the center of the target to the
point where the ball hit. The objective of the research was to assess if
footwear could affect the accuracy of a soccer player.</p>
<p>The subjects wore five different soccer shoes and for one treatment
they kicked the ball in stocking feet. Due to the proprietary nature of
the data, the shoes are only labeled “A,” “B,” “C,” “D,” and “E” in the
article. Use the soccer shoes to answer the following questions.</p>
<p><img src = "Images/Step3.png"></p>
<div class="QuestionsHeading">
Answer the following questions:
</div>
<div class="Questions">
<ol style="list-style-type: decimal">
<li><strong>Give the relevant summary statistics</strong></li>
</ol>
<a href = "javascript:showhide('Q1')"><span
style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="Q1" style="display:none;">
<pre class="r"><code>library(mosaic)
favstats(values ~ ind, data = soccer)</code></pre>
<p>Using the code above, we can pull out the important values.</p>
<table>
<thead>
<tr class="header">
<th align="left">ind</th>
<th align="left">N</th>
<th align="left">Mean</th>
<th align="left">Std. Deviation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">shoe_a</td>
<td align="left">20</td>
<td align="left">33.10</td>
<td align="left">5.230</td>
</tr>
<tr class="even">
<td align="left">shoe_b</td>
<td align="left">20</td>
<td align="left">32.70</td>
<td align="left">5.430</td>
</tr>
<tr class="odd">
<td align="left">shoe_c</td>
<td align="left">20</td>
<td align="left">29.45</td>
<td align="left">5.216</td>
</tr>
<tr class="even">
<td align="left">shoe_d</td>
<td align="left">20</td>
<td align="left">32.00</td>
<td align="left">7.291</td>
</tr>
<tr class="odd">
<td align="left">shoe_e</td>
<td align="left">20</td>
<td align="left">32.20</td>
<td align="left">5.569</td>
</tr>
<tr class="even">
<td align="left">socks</td>
<td align="left">20</td>
<td align="left">35.25</td>
<td align="left">6.382</td>
</tr>
</tbody>
</table>
</div>
<p><br></p>
<ol start="2" style="list-style-type: decimal">
<li><strong>Make an appropriate graph to illustrate the
data</strong></li>
</ol>
<a href = "javascript:showhide('Q2')"><span
style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="Q2" style="display:none;">
<pre class="r"><code>soccer</code></pre>
<pre><code>##     values    ind
## 1       35 shoe_a
## 2       32 shoe_a
## 3       39 shoe_a
## 4       44 shoe_a
## 5       35 shoe_a
## 6       27 shoe_a
## 7       28 shoe_a
## 8       31 shoe_a
## 9       39 shoe_a
## 10      38 shoe_a
## 11      37 shoe_a
## 12      34 shoe_a
## 13      22 shoe_a
## 14      29 shoe_a
## 15      35 shoe_a
## 16      35 shoe_a
## 17      26 shoe_a
## 18      29 shoe_a
## 19      34 shoe_a
## 20      33 shoe_a
## 21      30 shoe_b
## 22      27 shoe_b
## 23      27 shoe_b
## 24      38 shoe_b
## 25      36 shoe_b
## 26      31 shoe_b
## 27      36 shoe_b
## 28      36 shoe_b
## 29      25 shoe_b
## 30      37 shoe_b
## 31      26 shoe_b
## 32      40 shoe_b
## 33      40 shoe_b
## 34      39 shoe_b
## 35      41 shoe_b
## 36      29 shoe_b
## 37      31 shoe_b
## 38      31 shoe_b
## 39      26 shoe_b
## 40      28 shoe_b
## 41      25 shoe_c
## 42      40 shoe_c
## 43      35 shoe_c
## 44      30 shoe_c
## 45      23 shoe_c
## 46      24 shoe_c
## 47      31 shoe_c
## 48      28 shoe_c
## 49      39 shoe_c
## 50      32 shoe_c
## 51      26 shoe_c
## 52      25 shoe_c
## 53      31 shoe_c
## 54      20 shoe_c
## 55      29 shoe_c
## 56      27 shoe_c
## 57      27 shoe_c
## 58      31 shoe_c
## 59      36 shoe_c
## 60      30 shoe_c
## 61      26 shoe_d
## 62      19 shoe_d
## 63      32 shoe_d
## 64      37 shoe_d
## 65      29 shoe_d
## 66      43 shoe_d
## 67      38 shoe_d
## 68      30 shoe_d
## 69      33 shoe_d
## 70      34 shoe_d
## 71      41 shoe_d
## 72      35 shoe_d
## 73      24 shoe_d
## 74      28 shoe_d
## 75      27 shoe_d
## 76      27 shoe_d
## 77      37 shoe_d
## 78      48 shoe_d
## 79      30 shoe_d
## 80      22 shoe_d
## 81      43 shoe_e
## 82      30 shoe_e
## 83      38 shoe_e
## 84      36 shoe_e
## 85      27 shoe_e
## 86      30 shoe_e
## 87      34 shoe_e
## 88      25 shoe_e
## 89      38 shoe_e
## 90      37 shoe_e
## 91      24 shoe_e
## 92      29 shoe_e
## 93      26 shoe_e
## 94      27 shoe_e
## 95      35 shoe_e
## 96      29 shoe_e
## 97      28 shoe_e
## 98      33 shoe_e
## 99      42 shoe_e
## 100     33 shoe_e
## 101     34  socks
## 102     37  socks
## 103     46  socks
## 104     39  socks
## 105     27  socks
## 106     37  socks
## 107     41  socks
## 108     37  socks
## 109     36  socks
## 110     28  socks
## 111     43  socks
## 112     36  socks
## 113     40  socks
## 114     26  socks
## 115     40  socks
## 116     44  socks
## 117     27  socks
## 118     33  socks
## 119     28  socks
## 120     26  socks</code></pre>
<pre class="r"><code>boxplot(values ~ ind, data = soccer,
        col = &quot;tan3&quot;, 
        main = &quot;Soccer Shoes vs. Socks and Shooting Accuracy&quot;,
        xlab = &quot;Footwear&quot;,
        ylab = &quot;Accuracy&quot;)</code></pre>
<p><img src="Lesson14_files/figure-html/soccer_boxplot-1.png" width="672" /></p>
</div>
<p><br></p>
<ol start="3" style="list-style-type: decimal">
<li>Based on what you have seen so far, does it appear that there is a
significant difference between the mean accuracy of the kicks using the
six types of footwear?</li>
</ol>
<a href = "javascript:showhide('Q3')"><span
style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="Q3" style="display:none;">
<ul>
<li>Just by looking at the boxplots we can see that there is a
difference, but we do not know if there is a statistically significant
difference between the mean accuracy of the kicks using the six
different types of footwear until we perform an hypothesis test for
several means.<br />
</li>
</ul>
</div>
<p><br></p>
<ol start="4" style="list-style-type: decimal">
<li>Which types of footwear seem to be giving the greatest
accuracy?</li>
</ol>
<a href = "javascript:showhide('Q4')"><span
style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="Q4" style="display:none;">
<ul>
<li>Based on the boxplot, it appears that “socks” seem to give the
greatest accuracy. This is substantiated by looking at the sample means
in the numerical summary where “socks” has a mean accuracy of 35.25,
which is bigger than any other mean.</li>
</ul>
</div>
<p> </p>
</div>
<p><br></p>
<p><img src = "Images/Step4.png"></p>
<div class="QuestionsHeading">
Answer the following questions:
</div>
<div class="Questions">
<ol start="5" style="list-style-type: decimal">
<li><strong>Verify the requirements have been met</strong></li>
</ol>
<a href = "javascript:showhide('Q5')"><span
style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="Q5" style="display:none;">
<ul>
<li>The boxplots all look fairly symmetric in the graph above. The
median line isn’t exactly in the middle of each box, but there are not
any outliers and there isn’t any overly skewed box in the graph, so it
seems okay to consider this data as normally distributed.<br />
</li>
<li>We compute the variance of the groups using the following
command:</li>
</ul>
<pre class="r"><code>var(values ~ ind, data=soccer)</code></pre>
<pre><code>##   shoe_a   shoe_b   shoe_c   shoe_d   shoe_e    socks 
## 27.35789 29.48421 27.20789 53.15789 31.01053 40.72368</code></pre>
<p>The largest variance (53.158) is not more than four times the
smallest (27.208), so the assumption of equal variances is
satisfied.</p>
</div>
<p><br></p>
<ol start="6" style="list-style-type: decimal">
<li><strong>Give the test statistic and its value</strong></li>
</ol>
<a href = "javascript:showhide('Q6')"><span
style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="Q6" style="display:none;">
<pre class="r"><code>aov_output &lt;- aov(values ~ ind, data = soccer)
summary(aov_output)</code></pre>
<pre><code>##              Df Sum Sq Mean Sq F value Pr(&gt;F)  
## ind           5    352   70.36    2.02 0.0809 .
## Residuals   114   3970   34.82                 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<ul>
<li><span class="math inline">\(F\)</span> statistic = 2.02</li>
</ul>
</div>
<p><br></p>
<ol start="7" style="list-style-type: decimal">
<li><strong>State the degrees of freedom</strong></li>
</ol>
<a href = "javascript:showhide('Q7')"><span
style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="Q7" style="display:none;">
<ul>
<li>There are 5 and 114 degrees of freedom</li>
</ul>
</div>
<p><br></p>
<ol start="8" style="list-style-type: decimal">
<li><strong>Mark the test statistic and <span
class="math inline">\(P\)</span>-value on a graph of the sampling
distribution</strong></li>
</ol>
<a href = "javascript:showhide('Q8')"><span
style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="Q8" style="display:none;">
<p>This is included just to remind you that the p-value is the area to
the right of the F-statistic in the F-distribution.</p>
<p><img src = "Images/SoccerShoes-SamplingDist.png"></p>
<!--
If you are curious, this could be done in R using the code


```r
curve(df(x, 5, 114), from = 0, to = 10)
abline(v = 2.02, h = 0)
```

<img src="Lesson14_files/figure-html/unnamed-chunk-15-1.png" width="672" />
-->
</div>
<p><br></p>
<ol start="9" style="list-style-type: decimal">
<li><strong>Find the <span class="math inline">\(P\)</span>-value and
compare it to the level of significance</strong></li>
</ol>
<a href = "javascript:showhide('Q9')"><span
style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="Q9" style="display:none;">
<ul>
<li><span class="math inline">\(P\text{-value} = 0.0809 &lt; 0.1 =
\alpha\)</span></li>
</ul>
</div>
<p><br></p>
<ol start="10" style="list-style-type: decimal">
<li><strong>State your decision</strong></li>
</ol>
<a href = "javascript:showhide('Q10')"><span
style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="Q10" style="display:none;">
<ul>
<li>Since the <span class="math inline">\(P\)</span>-value <span
class="math inline">\(= 0.0809 &lt; 0.1 = \alpha\)</span>, we reject the
null hypothesis.</li>
</ul>
</div>
<p> </p>
</div>
<p><br></p>
<p><img src = "Images/Step5.png"></p>
<div class="QuestionsHeading">
Answer the following questions:
</div>
<div class="Questions">
<ol start="11" style="list-style-type: decimal">
<li><strong>Present your conclusion in an English sentence, relating the
result to the context of the problem</strong></li>
</ol>
<a href = "javascript:showhide('Q11')"><span
style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="Q11" style="display:none;">
<ul>
<li>There is sufficient evidence to suggest that there is a difference
in the mean accuracy of the kicks for the various types of
footwear.<br />
</li>
</ul>
</div>
<p> </p>
</div>
<p><br></p>
</div>
</div>
<div id="summary" class="section level2">
<h2>Summary</h2>
<div class="SummaryHeading">
Remember…
</div>
<div class="Summary">
<ul>
<li><p><strong>ANOVA</strong> is used to compare the means for several
groups. The hypotheses for the test are always: <span
class="math display">\[
\begin{align}
H_0: &amp; ~ \textrm{All the means are equal} \\
H_a: &amp; ~ \textrm{At least one of the means differs}
\end{align}
\]</span></p></li>
<li><p>For ANOVA testing we use an <strong><span
class="math inline">\(F\)</span>-distribution</strong>, which is
right-skewed. The <span class="math inline">\(P\)</span>-value of an
ANOVA test is always the area to the right of the <span
class="math inline">\(F\)</span>-statistic.</p></li>
<li><p>We can conduct ANOVA testing when the following requirements are
satisfied:</p>
<ol style="list-style-type: decimal">
<li>The data come from a simple random sample.</li>
<li>The data are normally distributed within each group.
<ul>
<li>This is considered met unless one or more of the groups has a
<em>strongly</em> skewed distribution.</li>
</ul></li>
<li>The variance is constant.
<ul>
<li>This is satisfied when the largest variance is not more than four
times the smallest.</li>
</ul></li>
</ol></li>
<li><p>To perform an ANOVA in R, use the code
<code>aov_output &lt;- aov(...)</code> to run the test, then the code
<code>summary(aov_output)</code> to view the results.</p></li>
<li><p>If data are provided in “wide” format, they must first be
converted to “long” format before performing the ANOVA analysis. This
can be accomplished using the command
<code>new_data_frame &lt;- stack(Filter(is.numeric, old_data_frame))</code>
in R.</p></li>
</ul>
<p><br></p>
</div>
<p><br></p>
</div>
<div id="navigation" class="section level2">
<h2>Navigation</h2>
<center>
<table>
<colgroup>
<col width="38%" />
<col width="30%" />
<col width="30%" />
</colgroup>
<thead>
<tr class="header">
<th align="center"><strong>Previous Reading</strong></th>
<th align="center"><strong>This Reading</strong></th>
<th align="center"><strong>Next Reading</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"><a href="Lesson13.html">Lesson 13: <br> Inference for
Two Means: Independent Samples</a></td>
<td align="center">Lesson 14: <br> Inference for Several Means
(ANOVA)</td>
<td align="center"><a href="Lesson15.html">Lesson 15: <br> Review for
Exam 2</a></td>
</tr>
</tbody>
</table>
</center>
</div>

<br />
<hr />
<p>Copyright &copy; 2020 Brigham Young University-Idaho. All rights reserved.</p>



</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
