<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Lesson 12: Inference for the Mean of Differences (Two Dependent Samples)</title>

<script src="site_libs/header-attrs-2.16/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cerulean.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>






<link rel="stylesheet" href="styles.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Math 221</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Unit 1
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="Lesson01_Campus.html">Lesson 1: (On Campus) Course Intro &amp; Probability</a>
    </li>
    <li>
      <a href="Lesson01.html">Lesson 1: (Online) Course Intro &amp; Probability</a>
    </li>
    <li>
      <a href="Lesson02.html">Lesson 2: The Statistical Process</a>
    </li>
    <li>
      <a href="Lesson03.html">Lesson 3: Describing Quantitative Data (Shape &amp; Center)</a>
    </li>
    <li>
      <a href="Lesson04.html">Lesson 4: Describing Quantitative Data (Spread)</a>
    </li>
    <li>
      <a href="Lesson05.html">Lesson 5: Normal Distributions</a>
    </li>
    <li>
      <a href="Lesson06.html">Lesson 6: The Central Limit Theorem</a>
    </li>
    <li>
      <a href="Lesson07.html">Lesson 7: Calculating Probabilities involving the Sample Mean</a>
    </li>
    <li>
      <a href="Lesson08.html">Lesson 8: Unit 1 Review</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Unit 2
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="Lesson09.html">Lesson 9: Hypothesis Test for One Mean (Sigma Known)</a>
    </li>
    <li>
      <a href="Lesson10.html">Lesson 10: Confidence Interval for One Mean (Sigma Known)</a>
    </li>
    <li>
      <a href="Lesson11.html">Lesson 11: Inference for One Mean (Sigma Unknown)</a>
    </li>
    <li>
      <a href="Lesson12.html">Lesson 12: Inference for Match Pairs</a>
    </li>
    <li>
      <a href="Lesson13.html">Lesson 13: Inference for Two Independent Samples</a>
    </li>
    <li>
      <a href="Lesson14.html">Lesson 14: Inference for Several Independent Samples</a>
    </li>
    <li>
      <a href="Lesson15.html">Lesson 15: Unit 2 Review</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Unit 3
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="Lesson16.html">Lesson 16: Describing Categorical Data</a>
    </li>
    <li>
      <a href="Lesson17.html">Lesson 17: Inference for One Proportion</a>
    </li>
    <li>
      <a href="Lesson18.html">Lesson 18: Inference for Two Proportions</a>
    </li>
    <li>
      <a href="Lesson19.html">Lesson 19: Inference for Independence of Categorical Data</a>
    </li>
    <li>
      <a href="Lesson20.html">Lesson 20: Unit 3 Review</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Unit 4
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="Lesson21.html">Lesson 21: Describing Bivariate Data</a>
    </li>
    <li>
      <a href="Lesson22.html">Lesson 22: Simple Linear Regression</a>
    </li>
    <li>
      <a href="Lesson23.html">Lesson 23: Inference for Bivariate Data</a>
    </li>
    <li>
      <a href="Lesson24.html">Lesson 24: Unit 4 Review</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="RHelp.html">R Help</a>
</li>
<li>
  <a href="Data.html">Data</a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Lesson 12: Inference for the Mean of
Differences (Two Dependent Samples)</h1>

</div>

<div id="TOC">
<ul>
<li><a href="#lesson-outcomes" id="toc-lesson-outcomes">Lesson
Outcomes</a></li>
<li><a href="#introduction-to-paired-data"
id="toc-introduction-to-paired-data">Introduction to Paired
Data</a></li>
<li><a href="#hypothesis-tests" id="toc-hypothesis-tests">Hypothesis
Tests</a>
<ul>
<li><a href="#mahons-weight-loss-study"
id="toc-mahons-weight-loss-study">Mahon’s Weight Loss Study</a></li>
<li><a href="#r-instructions-for-computing-paired-differences"
id="toc-r-instructions-for-computing-paired-differences">R Instructions
for Computing Paired Differences</a></li>
<li><a href="#hypothesis-test-for-mahons-weight-loss-data"
id="toc-hypothesis-test-for-mahons-weight-loss-data">Hypothesis Test for
Mahon’s Weight Loss Data</a></li>
<li><a href="#r-instructions-for-a-paired-samples-t-test"
id="toc-r-instructions-for-a-paired-samples-t-test">R Instructions for a
Paired Samples t Test</a></li>
<li><a href="#nosocomial-infections"
id="toc-nosocomial-infections">Nosocomial Infections</a></li>
<li><a href="#additional-worked-examples"
id="toc-additional-worked-examples">Additional Worked Examples</a></li>
</ul></li>
<li><a href="#confidence-intervals"
id="toc-confidence-intervals">Confidence Intervals</a>
<ul>
<li><a href="#mountain-pine-beetle-attacks"
id="toc-mountain-pine-beetle-attacks">Mountain Pine Beetle
Attacks</a></li>
<li><a href="#r-instructions-for-confidence-intervals"
id="toc-r-instructions-for-confidence-intervals">R Instructions for
Confidence Intervals</a></li>
<li><a href="#sleep-inducing-drugs"
id="toc-sleep-inducing-drugs">Sleep-Inducing Drugs</a></li>
</ul></li>
<li><a href="#summary" id="toc-summary">Summary</a></li>
<li><a href="#navigation" id="toc-navigation">Navigation</a></li>
</ul>
</div>

<script type = "text/javascript">
 function showhide(id) {
    var e = document.getElementById(id);
    e.style.display = (e.style.display =='block') ? 'none' : 'block';
 }
</script>
<!--
<div style = "float:right;width = 40%;">
<br/>
<div style = "padding-left:10%;">**Optional Lesson Video**</div>
<iframe width = "90%" align = "right" src = "https://www.youtube.com/embed/videoseries?list = PLaZryQtbPQC-jykAMUjbIFLALZmXRadUa" frameborder = "1" allow = "autoplay; encrypted-media" allowfullscreen></iframe>
</div>
-->
<div id="lesson-outcomes" class="section level2">
<h2>Lesson Outcomes</h2>
<a href = "javascript:showhide('outcome')"><span
style="font-size:8pt;">Show/Hide Outcomes</span></a>
<div id="outcome" style="display:none;">
<p>By the end of this lesson, you should be able to do the
following.</p>
<ul>
<li>Apply a confidence interval for the mean of differences (two
dependent samples) using the following steps:
<ul>
<li>Determine the level of confidence</li>
<li>Create numerical and graphical summaries of the data</li>
<li>Create a confidence interval using software</li>
<li>Check the requirements of the confidence interval</li>
<li>Interpret a confidence interval for the mean of differences (two
dependent samples)</li>
</ul></li>
<li>Perform a hypothesis test for the mean of differences (two dependent
samples) using the following steps:
<ul>
<li>State the null and alternative hypotheses</li>
<li>State the level of significance (α)</li>
<li>Create numerical and graphical summaries of the data</li>
<li>Calculate the test-statistic, degrees of freedom and P-value of the
test using software</li>
<li>Assess statistical significance by comparing the P-value to the
level of significance (α)</li>
<li>State the appropriate conclusion for the hypothesis test</li>
<li>Check the requirements for the hypothesis test</li>
</ul></li>
</ul>
</div>
<p><br></p>
</div>
<div id="introduction-to-paired-data" class="section level2">
<h2>Introduction to Paired Data</h2>
<p>It is very common for researchers to conduct studies in which they
administer a pre-test to a group of individuals, provide some treatment
to those individuals, and then give a post-test to each individual.
Since each individual in the study has both a pre-test and post-test
measurement, researchers can use the difference between the post- and
pre-test measurements as a measure of the effect the treatment had on
each particular individual. The average of these differences can also be
computed to find the average effect the treatment had on indvidiuals. We
call this the <em>mean of the differences</em> for paired data.</p>
<p>These study designs are also called a <strong>matched-pairs</strong>
design or we say we have <strong>dependent samples</strong>.
Matched-pairs (or <strong>paired-data</strong>) designs typically
involve only one population, and a pair of observations is drawn on the
individuals selected for the sample (i.e., there are two measurements
per individual). If an individual is selected to participate in the
pre-test (i.e., they are selected to be part of group 1), they are
automatically selected to participate in the post-test (i.e., they are
chosen to be in group 2 automatically.)</p>
<p>A hypothesis test for two means with paired data (dependent samples)
is conducted in the same way as a hypothesis test for a single mean with
<span class="math inline">\(\sigma\)</span> unknown, the one-sample t
test. The only exception is that the pairs of data must be subtracted
before you start any computations. From a practical perspective, after
you compute the differences for each matched pair, then you apply the
one-sample procedures you have already learned to those differences.</p>
<p>We will first explore an application of pre- and post-testing in a
weight loss study.</p>
</div>
<div id="hypothesis-tests" class="section level2">
<h2>Hypothesis Tests</h2>
<p><img src = "Images/StepsAll.png"></p>
<div id="mahons-weight-loss-study" class="section level3">
<h3>Mahon’s Weight Loss Study</h3>
<p><strong>Background</strong></p>
<p>Annie Mahon and other researchers in Wayne Campbell’s nutrition lab
studied the weight loss of <span class="math inline">\(n = 27\)</span>
middle aged women who consumed a prescribed low-calorie diet.
<!--<cite>Mahon07</cite>--> The women’s weights were recorded (in
kilograms) at the beginning of the study and after the nine-week diet
period. The data are given in the data frame <code>weight_loss</code>.
You can access this data frame by running the command</p>
<pre class="r"><code>  load(url(&quot;https://byuistats.github.io/M221R/data/L12.RData&quot;))</code></pre>
<p>in R. An excerpt of the data is shown below.</p>
<table>
<thead>
<tr class="header">
<th align="left">
<p>
Subject
</p>
</th>
<th align="left">
<p>
Pre Weight (kg)
</p>
</th>
<th align="left">
<p>
Post Weight (kg)
</p>
</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>
<p>
1
</p>
</td>
<td>
<p>
62.5
</p>
</td>
<td>
<p>
56.1
</p>
</td>
</tr>
<tr class="even">
<td>
<p>
2
</p>
</td>
<td>
<p>
88.8
</p>
</td>
<td>
<p>
80.2
</p>
</td>
</tr>
<tr class="odd">
<td>
<p>
3
</p>
</td>
<td>
<p>
74.7
</p>
</td>
<td>
<p>
70.8
</p>
</td>
</tr>
<tr class="even">
<td>
<p>
<span class="math inline">\(\vdots\)</span>
</p>
</td>
<td>
<p>
<span class="math inline">\(\vdots\)</span>
</p>
</td>
<td>
<p>
<span class="math inline">\(\vdots\)</span>
</p>
</td>
</tr>
<tr class="odd">
<td>
<p>
26
</p>
</td>
<td>
<p>
76.3
</p>
</td>
<td>
<p>
73.8
</p>
</td>
</tr>
<tr class="even">
<td>
<p>
27
</p>
</td>
<td>
<p>
82.1
</p>
</td>
<td>
<p>
77.9
</p>
</td>
</tr>
<tr class="odd">
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
<p>Notice the structure of the data. The weight of each subject was
measured before the study and at the conclusion of the study. Each
person provided a pre-study weight and a post-study weight. Stated
differently, the pre-study weights and the post-study weights are
paired. For each row of data, both of these numbers came from the same
person. When we collect two observations of the same measurement on each
subject, we call it <strong>paired data</strong>. Sometimes paired data
are called <strong>dependent samples</strong>.</p>
<div class="QuestionsHeading">
Answer the following question:
</div>
<div class="Questions">
<ol style="list-style-type: decimal">
<li>The researchers measured the initial weights of the women prior to
the study, even though they were not particularly interested in this
value. What was the purpose of measuring the pre-study weights?</li>
</ol>
<a href = "javascript:showhide('Q1')"><span
style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="Q1" style="display:none;">
<ul>
<li>The goal of the study is to determine how much the women’s weight
change as as result of the study. The researchers must measure the
women’s weights at the beginning of the study, so they can subtract the
initial (pre-study) weight of each woman from her final (post-study)
weight.</li>
</ul>
</div>
<p> </p>
</div>
<p><br></p>
</div>
<div id="r-instructions-for-computing-paired-differences"
class="section level3">
<h3>R Instructions for Computing Paired Differences</h3>
<p>The researchers are not interested in the weights of the women, they
are more interested in the <em>change</em> in the women’s weights. This
will give them a measure of the effectiveness of the low-calorie diet.
In other words, they are interested in the difference of the weights
after the study compared with before: <span
class="math display">\[\text{Difference} = \text{Post Weight} -
\text{Pre Weight}\]</span></p>
<p>We can calculate the difference (or change) in weight for each woman
in the study:</p>
<table>
<thead>
<tr class="header">
<th align="left">
<p>
Subject
</p>
</th>
<th align="left">
<p>
Post Weight (kg)
</p>
</th>
<th align="left">
<p>
Pre Weight (kg)
</p>
</th>
<th align="left">
<p>
Difference in Weight (kg)
</p>
</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>
<p>
1
</p>
</td>
<td>
<p>
56.1
</p>
</td>
<td>
<p>
62.5
</p>
</td>
<td>
<p>
56.1 <span class="math inline">\(-\)</span> 62.5 = -6.4
</p>
</td>
</tr>
<tr class="even">
<td>
<p>
2
</p>
</td>
<td>
<p>
80.2
</p>
</td>
<td>
<p>
88.8
</p>
</td>
<td>
<p>
80.2 <span class="math inline">\(-\)</span> 88.8 = -8.6
</p>
</td>
</tr>
<tr class="odd">
<td>
<p>
3
</p>
</td>
<td>
<p>
70.8
</p>
</td>
<td>
<p>
74.7
</p>
</td>
<td>
<p>
70.8 <span class="math inline">\(-\)</span> 74.7 = -3.9
</p>
</td>
</tr>
<tr class="even">
<td>
<p>
<span class="math inline">\(\vdots\)</span>
</p>
</td>
<td>
<p>
<span class="math inline">\(\vdots\)</span>
</p>
</td>
<td>
<p>
<span class="math inline">\(\vdots\)</span>
</p>
</td>
<td>
<p>
<span class="math inline">\(\vdots\)</span>
</p>
</td>
</tr>
<tr class="odd">
<td>
<p>
26
</p>
</td>
<td>
<p>
73.8
</p>
</td>
<td>
<p>
76.3
</p>
</td>
<td>
<p>
73.8 <span class="math inline">\(-\)</span> 76.3 = -2.5
</p>
</td>
</tr>
<tr class="even">
<td>
<p>
27
</p>
</td>
<td>
<p>
77.9
</p>
</td>
<td>
<p>
82.1
</p>
</td>
<td>
<p>
77.9 <span class="math inline">\(-\)</span> 82.1 = -4.2
</p>
</td>
</tr>
</tbody>
</table>
<p><a name = "SubtractDifferences"></a></p>
<div class="SoftwareHeading">
R Instructions
</div>
<div class="Software">
<p>To compute the <em>differences</em> within each paired set of
measurements in R, begin by reading in the <code>weight_loss</code> data
into RStudio. You can access this data frame by running the command
<code>load(url("https://byuistats.github.io/M221R/data/L12.RData"))</code>
in R.</p>
<p>Then, calculate the <em>differences</em> using the assignment
operator <code>&lt;-</code> and the selection operator
<code>$</code>:</p>
<pre class="r"><code>weight_loss$difference &lt;- weight_loss$post - weight_loss$pre</code></pre>
<p>Here we chose the order Post - Pre so that a positive difference
would show an increase in weight (kg) from Pre-Weight to Post-Weight and
a negative difference would show a decrease in weight (kg) from
Pre-Weight to Post-Weight. Thus, a negative difference means the woman
lost weight. This is usually the preferred order of subtraction with
“Post vs. Pre” studies.</p>
<p>Once the differences are computed, we can compute the mean, median,
standard deviation and so on using codes like the following.</p>
<pre class="r"><code>library(mosaic)
favstats(weight_loss$difference)</code></pre>
<pre><code>##    min   Q1 median   Q3  max      mean       sd  n missing
##  -13.6 -8.9   -6.7 -4.2 -1.6 -6.803704 3.172051 27       0</code></pre>
<p>So we find that</p>
<p><span class="math display">\[
  \bar{d} = -6.804 \\
  s_d = 3.172 \\
  n = 27
\]</span></p>
<p>Notice that we use <span class="math inline">\(\bar d\)</span> to
represent the mean of the difference where <span class="math inline">\(d
= post-pre\)</span>. We use a subscript of <span
class="math inline">\(d\)</span> to indicate that the standard deviation
we computed is the standard deviation of the differences.</p>
<p>We make a histogram and boxplot of the differences:</p>
<pre class="r"><code>hist(weight_loss$difference,
     col = &quot;tan3&quot;,
     xlab = &quot;Weight Change in Kilograms (Post - Pre)&quot;,
     main = &quot;Weight Loss Study&quot;) </code></pre>
<p><img src="Lesson12_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<pre class="r"><code>boxplot(weight_loss$difference,
        horizontal=TRUE,
        col = &quot;tan3&quot;,
        xlab = &quot;Weight Change in Kilograms (Post - Pre)&quot;,
        main = &quot;Weight Loss Study&quot;) </code></pre>
<p><img src="Lesson12_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
</div>
<p><br></p>
<div class="QuestionsHeading">
Answer the following questions:
</div>
<div class="Questions">
<ol start="2" style="list-style-type: decimal">
<li>What is the difference in the post- and pre-study weights for the
first person included in the data file?</li>
</ol>
<a href = "javascript:showhide('Q2')"><span
style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="Q2" style="display:none;">
<p>The first difference is found by printing the differences to the
screen and looking at the first value. Do this by simply typing the name
of the object “differences.”</p>
<table>
<thead>
<tr class="header">
<th align="center">subject</th>
<th align="center">pre</th>
<th align="center">post</th>
<th align="center">difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">1</td>
<td align="center">62.5</td>
<td align="center">56.1</td>
<td align="center">-6.4</td>
</tr>
<tr class="even">
<td align="center">2</td>
<td align="center">88.8</td>
<td align="center">80.2</td>
<td align="center">-8.6</td>
</tr>
<tr class="odd">
<td align="center">3</td>
<td align="center">74.7</td>
<td align="center">70.8</td>
<td align="center">-3.9</td>
</tr>
<tr class="even">
<td align="center">4</td>
<td align="center">98.6</td>
<td align="center">97.0</td>
<td align="center">-1.6</td>
</tr>
<tr class="odd">
<td align="center">5</td>
<td align="center">78.1</td>
<td align="center">69.1</td>
<td align="center">-9.0</td>
</tr>
<tr class="even">
<td align="center">6</td>
<td align="center">73.8</td>
<td align="center">63.8</td>
<td align="center">-10.0</td>
</tr>
<tr class="odd">
<td align="center">7</td>
<td align="center">87.0</td>
<td align="center">81.9</td>
<td align="center">-5.1</td>
</tr>
<tr class="even">
<td align="center">8</td>
<td align="center">62.1</td>
<td align="center">53.3</td>
<td align="center">-8.8</td>
</tr>
<tr class="odd">
<td align="center">9</td>
<td align="center">60.7</td>
<td align="center">56.5</td>
<td align="center">-4.2</td>
</tr>
<tr class="even">
<td align="center">10</td>
<td align="center">76.2</td>
<td align="center">71.8</td>
<td align="center">-4.4</td>
</tr>
<tr class="odd">
<td align="center">11</td>
<td align="center">81.3</td>
<td align="center">76.6</td>
<td align="center">-4.7</td>
</tr>
<tr class="even">
<td align="center">12</td>
<td align="center">79.4</td>
<td align="center">68.6</td>
<td align="center">-10.8</td>
</tr>
<tr class="odd">
<td align="center">13</td>
<td align="center">89.9</td>
<td align="center">84.0</td>
<td align="center">-5.9</td>
</tr>
<tr class="even">
<td align="center">14</td>
<td align="center">71.8</td>
<td align="center">58.2</td>
<td align="center">-13.6</td>
</tr>
<tr class="odd">
<td align="center">15</td>
<td align="center">73.7</td>
<td align="center">69.9</td>
<td align="center">-3.8</td>
</tr>
<tr class="even">
<td align="center">16</td>
<td align="center">80.1</td>
<td align="center">73.2</td>
<td align="center">-6.9</td>
</tr>
<tr class="odd">
<td align="center">17</td>
<td align="center">64.2</td>
<td align="center">61.4</td>
<td align="center">-2.8</td>
</tr>
<tr class="even">
<td align="center">18</td>
<td align="center">78.9</td>
<td align="center">65.9</td>
<td align="center">-13.0</td>
</tr>
<tr class="odd">
<td align="center">19</td>
<td align="center">61.9</td>
<td align="center">53.5</td>
<td align="center">-8.4</td>
</tr>
<tr class="even">
<td align="center">20</td>
<td align="center">79.2</td>
<td align="center">71.1</td>
<td align="center">-8.1</td>
</tr>
<tr class="odd">
<td align="center">21</td>
<td align="center">77.6</td>
<td align="center">68.1</td>
<td align="center">-9.5</td>
</tr>
<tr class="even">
<td align="center">22</td>
<td align="center">66.9</td>
<td align="center">63.1</td>
<td align="center">-3.8</td>
</tr>
<tr class="odd">
<td align="center">23</td>
<td align="center">77.0</td>
<td align="center">70.2</td>
<td align="center">-6.8</td>
</tr>
<tr class="even">
<td align="center">24</td>
<td align="center">99.6</td>
<td align="center">89.4</td>
<td align="center">-10.2</td>
</tr>
<tr class="odd">
<td align="center">25</td>
<td align="center">73.9</td>
<td align="center">67.2</td>
<td align="center">-6.7</td>
</tr>
<tr class="even">
<td align="center">26</td>
<td align="center">76.3</td>
<td align="center">73.8</td>
<td align="center">-2.5</td>
</tr>
<tr class="odd">
<td align="center">27</td>
<td align="center">82.1</td>
<td align="center">77.9</td>
<td align="center">-4.2</td>
</tr>
</tbody>
</table>
<p>The first difference is <span class="math inline">\(-6.4\)</span>.
So, the first woman included in the study lost 6.4 kg during the course
of the study.</p>
</div>
<p><br></p>
<ol start="3" style="list-style-type: decimal">
<li>What is the mean of the <em>differences</em>? Said differently, what
is the mean change in the weights of the women who participated in the
study?</li>
</ol>
<a href = "javascript:showhide('Q3')"><span
style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="Q3" style="display:none;">
<p>As shown in the output above,</p>
<center>
<span class="math display">\[
\bar{d} = -6.804 \ \text{kg}
\]</span>
</center>
</div>
<p><br></p>
<ol start="4" style="list-style-type: decimal">
<li>Interpret the value you calculated in Question 3.</li>
</ol>
<a href = "javascript:showhide('Q4')"><span
style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="Q4" style="display:none;">
<ul>
<li>The mean weight change experienced by the women in the study was
<span class="math inline">\(-6.804\)</span> kg. Because we calculated
Post-Pre, the <em>negative</em> mean difference indicates the Pre weight
was higher than the Post weight. In other words, there was a mean weight
<em>loss</em> of <span class="math inline">\(6.804\)</span> kg.</li>
</ul>
</div>
<p> </p>
</div>
<br>
</div>
<p><br></p>
<p><strong>Relationship to a One Sample t-test</strong></p>
<p>After you have subtracted the pre-study weights from the post-study
weights, you are left with a column of differences. We will denote the
pre-study weights by <span class="math inline">\(x_1\)</span> and the
post-study weights by <span class="math inline">\(x_2\)</span>. Then,
the differences can be denoted as <span class="math inline">\(d = x_2 -
x_1\)</span>. The difference, <span class="math inline">\(d\)</span>, is
defined as the change in the volunteer’s weight during the study.</p>
<p>After computing the differences, we do not use the data for the
individual groups anymore. The researchers are not interested in the
values of the women’s weights at the beginning of the study or at the
end of the study. They are interested in the difference in the weights
after the participants complete the study.</p>
<p>After we subtract, we can conduct a hypothesis test to determine if
the mean of the differences is less than zero. We use the symbol <span
class="math inline">\(\mu_d\)</span> to represent the true mean
difference in the weights of women who follow the diet prescribed in
this study. The null hypotheses is that the true mean difference is zero
(<span class="math inline">\(\mu_d = 0\)</span>). In other words, the
null hypothesis states that the prescribed diet does not influence the
weights of women. The alternative hypothesis is that there is a decrease
in the weights of the women, in other words, that the true mean
difference is less than zero (<span class="math inline">\(\mu_d &lt;
0\)</span>).</p>
<p>Notice that this is essentially a one-sample t-test where the data
are the <em>differences in the women’s weights</em>. We have one column
of data, the differences. We are testing whether the true mean
difference is less than zero (or not equal to zero, or greater than
zero). So, a test for the <em>differences of matched pairs</em> with
dependent samples is just like a test for one mean with <span
class="math inline">\(\sigma\)</span> unknown.</p>
<p>In the hypothesis test, we will refer to the variable representing
the differences as <span class="math inline">\(d\)</span>. We will use
this notation throughout the hypothesis test. For example, the true
population mean will be labeled <span
class="math inline">\(\mu_d\)</span> and the sample mean will be labeled
<span class="math inline">\(\bar d\)</span>. The sample standard
deviation of the differences is denoted <span
class="math inline">\(s_d\)</span>.</p>
</div>
<div id="hypothesis-test-for-mahons-weight-loss-data"
class="section level3">
<h3>Hypothesis Test for Mahon’s Weight Loss Data</h3>
<p><img src = "Images/Step1.png"></p>
<p><strong>Summarize the relevant background information</strong></p>
<p>Twenty-seven women participated in a nine week weight loss study.
During the study period, the participants were provided a reduced
calorie diet. Their weights in kilograms were recorded at the beginning
of the study and nine weeks later. The difference of the weights is
defined as the post-study weights minus the pre-study weights. The
researchers expected that the mean difference in the weights would be
negative–in other words, that the women would tend to lose weight.</p>
<p><strong>State the null and alternative hypotheses and the level of
significance</strong></p>
<p><span class="math display">\[
\begin{align}
H_0: &amp;~~ \mu_d = 0 \\
H_a: &amp;~~ \mu_d &lt; 0
\end{align}
\]</span></p>
<p>We will use the <span class="math inline">\(\alpha = 0.05\)</span>
level of significance.</p>
<p><img src = "Images/Step2.png"></p>
<p><strong>Describe the data collection procedures</strong></p>
<p>The women’s weights were recorded at the beginning of the study. The
women were provided a reduced calorie diet for nine weeks. Then, their
weights were measured again at the end of the study. A calibrated scale
was used to provide an accurate weight.</p>
<p><img src = "Images/Step3.png"></p>
<p><strong>Give the relevant summary statistics</strong></p>
<p><img src="Lesson12_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p><img src="Lesson12_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>From the R output demonstrated previously, we can see a histogram of
the data and get the following numerical summaries:</p>
<p><span class="math display">\[
\begin{align}
\bar d &amp; = -6.804 \\
s_d &amp; = 3.172 \\
n &amp; = 27
\end{align}
\]</span></p>
<p><img src = "Images/Step4.png"></p>
<p><strong>Verify the requirements have been met</strong></p>
<p>Like the one-sample t-test, this procedure is robust, meaning that it
is not very sensitive to the requirements. If they are only mildly
violated, the test will still give reasonably good results.</p>
<p>The requirements for this procedure are the same as the requirements
for a one-sample t-test:</p>
<ul>
<li><p><strong>the data represent a simple random sample from the
population</strong></p>
<p>The subjects were recruited via advertisements for a research study.
The participants volunteered to participate. It is not a simple random
sample of all middle-aged women, so there could be some selection bias
of the sample that would invalidate the results, but there is nothing
obvious about how the participants were selected to immediately
invalidate the results.</p>
<p>From a practical perspective, it is impossible to get a simple random
sample of people in the general population. When research trials are
conducted, people must volunteer to participate. This can lead to a
selection bias, but is the accepted practice.</p></li>
<li><p><strong>the mean of the differences <span
class="math inline">\(\bar{d}\)</span> follows a normal
distribution</strong></p>
<p>We will assume the requirement of normality of <span
class="math inline">\(\bar{d}\)</span> is satisfied for Mahon’s data.
Though the sample size (n = 27) is not quite up to 30, the histogram of
differences looks fairly normal, so <span class="math inline">\(\bar
d\)</span> will be approximately normal and the requirement is
satisfied. If the data had been highly skewed, or there was a more
pronounced bimodal pattern in the histogram, then we would be worried
about the results of the test and would have recommended they redo the
study with a larger sample size in order to have confidence in the
results of the t-test.</p></li>
</ul>
<p><strong>Give the test statistic and its value</strong></p>
</div>
<div id="r-instructions-for-a-paired-samples-t-test"
class="section level3">
<h3>R Instructions for a Paired Samples t Test</h3>
<div class="SoftwareHeading">
R Instructions
</div>
<div class="Software">
<p>To perform a paired samples t test in R, first compute the
<em>differences</em> within each paired set of measurements in R as was
<a
href="Lesson12.html#r-instructions-for-computing-paired-differences">shown
previously</a>.</p>
<p>Then, run a t test on the differences. Since the null hypothesis for
the Mahon Weight Loss study was <span class="math inline">\(H_0: \mu_d =
0\)</span>, we use <code>t.test(..., mu = 0)</code>. Since the
alternative hypothesis was that <span class="math inline">\(H_a: \mu_d
&lt; 0\)</span>, we use the code
<code>t.test(..., alternative = "less")</code>. Putting this all
together we have the following.</p>
<pre class="r"><code>t.test(weight_loss$difference, 
       mu = 0, 
       alternative = &quot;less&quot;,
       conf.level = 0.95)</code></pre>
<pre><code>
    One Sample t-test

data:  weight_loss$difference
t = -11.145, df = 26, p-value = 1.059e-11
alternative hypothesis: true mean is less than 0
95 percent confidence interval:
     -Inf -5.76249
sample estimates:
mean of x 
-6.803704 </code></pre>
</div>
<p><br></p>
<p>The test statistic for a test involving paired data when <span
class="math inline">\(\sigma\)</span> is unknown is a <span
class="math inline">\(t\)</span>. For this situation, the value is:
<span class="math display">\[t = \frac{-6.804 - 0}{3.17/\sqrt{27}} =
-11.145\]</span> See that this calculation matches the test statistic
given in the R output. The degrees of freedom and p-value can also be
found in the R output.</p>
<p><strong>State the degrees of freedom</strong></p>
<p>The degrees of freedom are one less than the sample size. They are
also shown automatically in the output of the test results.</p>
<p><span class="math display">\[df = n - 1 = 27 - 1 = 26\]</span></p>
<p><strong>Find the <span class="math inline">\(P\)</span>-value and
compare it to the level of significance</strong></p>
<p><span class="math display">\[
P\text{-value} = 1.059 \times 10^{-11} &lt; 0.05 = \alpha
\]</span></p>
<p><strong>State your decision</strong></p>
<p>Since the <span class="math inline">\(P\)</span>-value is less than
the level of significance, we reject the null hypothesis.</p>
<p><img src = "Images/Step5.png"></p>
<p><strong>Present your conclusion in an English sentence, relating the
result to the context of the problem</strong></p>
<p>There is sufficient evidence to suggest that the reduced calorie diet
used in this study results in weight loss for middle-aged women with the
average weight loss around 6.804 kg. <br></p>
<p><img src = "Images/StepsAll.png"></p>
</div>
<div id="nosocomial-infections" class="section level3">
<h3>Nosocomial Infections</h3>
<p><span id="id_17:IntroToNosocomialInfections"></span></p>
<p><img src = "Images/Step1.png"></p>
<p><strong>Summarize the relevant background information</strong></p>
<p>Matched-pairs designs are not just used in pre- and post-test
situations. They are also used in situations where it is not possible to
randomly assign subjects to treatment groups because of ethical reasons.
For example, nosocomial (pronounced: NO-suh-KOH-MEE-uhl) infections are
infections that occur in hospitals, but are not a result of the original
condition. An example of a nosocomial infection is when a heart attack
patient develops a staph infection at the site of an IV injection. The
infection was not caused by the heart attack, but it was acquired in the
hospital. Nosocomial infections are very dangerous and may result in
longer recovery times or increased death rates.</p>
<p><img src = "Images/Pneumonia-CDC-5803.png"></p>
<p>Health care providers suspect that nosocomial infections increase the
amount of time required to recover from an illness or injury. In
controlled experiments, subjects (e.g., patients) are randomly assigned
to treatments. However, it is not ethical to give patients a nosocomial
infection in order to determine if it increases the duration of their
hospital stay! At best, we can collect information on the duration of
hospital stays for patients who acquire nosocomial infections and
compare them to the duration of the stays for patients who do not.</p>
<p>There are many factors that affect the amount of time that a patient
will need to stay in the hospital, including: nature of illness, types
of procedures conducted, overall health, gender, age, etc. How can
health care practitioners assess the effect of a nosocomial infection in
the presence of so many other variables?</p>
<p>One way is to match a patient who develops a nosocomial infection
with another one who has similar characteristics (illness, procedures,
health, gender, age group, etc.) but does not develop a nosocomial
infection. Now, the patients are matched into pairs with similar
characteristics, where the principle difference between the members of
each pair is whether or not they acquired a nosocomial infection.</p>
<p>By pairing the patients according to specific characteristics, the
researchers can now subtract to observe a difference in their recovery
times. In this way, it is possible to assess if nosocomial infections
increase the mean duration of a hospital stay. Some researchers
conducted such a study in which 52 pairs of patients were matched based
on clinical characteristics. A patient with a nosocomial infection was
matched as closely as possible to a similar case where there was no
nosocomial infection. Patients who died were excluded from the study
<!--<cite>Vegas93</cite>-->. The lengths of the hospital stays (in days)
for these patients are given in the data frame
<code>hospital_infections</code>. You can access this data frame by
running the command
<code>load(url("https://byuistats.github.io/M221R/data/L12.RData"))</code>
in R.</p>
<p>The difference, <span class="math inline">\(d\)</span>, is defined as
the duration of the hospital stay of the individual in the pair with the
nosocomial infection minus the duration of the stay for the individual
who did not get a nosocomial infection: <span class="math display">\[
difference = infected - not_infected
\]</span> After computing the differences, we do not use the data for
the individual groups anymore. In fact, after we subtract, the
hypothesis test is conducted (essentially) like a one-sample test for a
single mean with <span class="math inline">\(\sigma\)</span>
unknown.</p>
<div class="QuestionsHeading">
Answer the following questions:
</div>
<div class="Questions">
<ol start="5" style="list-style-type: decimal">
<li><strong>State the null and alternative hypotheses and the level of
significance</strong></li>
</ol>
<a href = "javascript:showhide('Q5')"><span
style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="Q5" style="display:none;">
<p>The null hypothesis for paired data will always use <span
class="math inline">\(\mu_d = 0\)</span>. In this study, we want to know
if the nosocomial infections are <em>increasing</em> the length of stay
of patients. Since we defined the differences as <span
class="math inline">\(infected - not_infected\)</span> then the
alternative hypothesis needs to show <span
class="math inline">\(infected\)</span> having longer durations than
those who are <span class="math inline">\(not_infected\)</span>, leading
to the Differences being positive, i.e., <span
class="math inline">\(\mu_d &gt; 0\)</span>.</p>
<center>
<span class="math display">\[
\begin{align}
H_0: &amp;~~ \mu_d = 0 \\
H_a: &amp;~~ \mu_d &gt; 0 \\
\end{align}
\]</span>
</center>
<ul>
<li>The level of significance was not specified in the problem. You can
choose any value you wish. The most common choices are 0.05, 0.01 and
0.1. We will illustrate this example with <span
class="math inline">\(\alpha = 0.05\)</span>.</li>
</ul>
</div>
<p> </p>
</div>
<p><br> In order to get the correct <span
class="math inline">\(P\)</span>-value, we need to indicate the proper
alternative hypothesis in the
<code>t.test(..., altnerative = "greater")</code>.</p>
<p><br></p>
<p><img src = "Images/Step2.png"></p>
<div class="QuestionsHeading">
Answer the following questions:
</div>
<div class="Questions">
<ol start="6" style="list-style-type: decimal">
<li><strong>Describe the data collection procedures</strong></li>
</ol>
<a href = "javascript:showhide('Q6')"><span
style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="Q6" style="display:none;">
<ul>
<li>Data were collected by matching hospital records of individuals who
were admitted to the hospital. Patient records were matched based on
their overall health and the reason they were admitted to the hospital.
In each pair, one patient developed a nosocomial infection and one did
not. Since the characteristics of the patients in the first group
determined which patients would be paired with them in the second group,
the data represent dependent samples.</li>
</ul>
</div>
<p> </p>
</div>
<p><br></p>
<p><img src = "Images/Step3.png"></p>
<div class="QuestionsHeading">
Answer the following questions:
</div>
<div class="Questions">
<ol start="7" style="list-style-type: decimal">
<li><strong>Give the relevant summary statistics</strong></li>
</ol>
<a href = "javascript:showhide('Q7')"><span
style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="Q7" style="display:none;">
<p>Recall that the differences <span class="math inline">\(d\)</span> in
the duration of the patient’s stay in the hospital were decided to be
computed in the order, <span class="math inline">\(difference = infected
- not_infected\)</span>.</p>
<pre class="r"><code>hospital_infections$difference &lt;- hospital_infections$infected - hospital_infections$not_infected</code></pre>
<p>The numerical summaries are computed using the command:</p>
<pre class="r"><code>favstats(hospital_infections$difference)</code></pre>
<pre><code> min Q1 median   Q3 max     mean       sd  n missing
 -22  2   11.5 19.5  39 11.38462 13.83255 52       0</code></pre>
<p><span class="math display">\[
\begin{align}
\bar d &amp; = 11.38 \\
s_d &amp; = 13.83 \\
n &amp; = 52
\end{align}
\]</span></p>
</div>
<p><br></p>
<ol start="8" style="list-style-type: decimal">
<li><strong>Make an appropriate graph to illustrate the
data</strong></li>
</ol>
<a href = "javascript:showhide('Q8')"><span
style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="Q8" style="display:none;">
<ul>
<li>Present a graph showing the differences.</li>
</ul>
<pre class="r"><code>hist(hospital_infections$difference, 
     main = &quot;Matched Pairs Study \n Nosocomial Infections&quot;, 
     xlab = &quot;Difference in Hospital Stay (infected - not_infected)&quot;)</code></pre>
<p><img src="Lesson12_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<pre class="r"><code>boxplot(hospital_infections$difference,
        horizontal=TRUE,
        main = &quot;Matched Pairs Study \n Nosocomial Infections&quot;,
        xlab = &quot;Difference in Hospital Stay (infected - not_infected)&quot;)</code></pre>
<p><img src="Lesson12_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
</div>
<p> </p>
</div>
<p><br></p>
<p><img src = "Images/Step4.png"></p>
<div class="QuestionsHeading">
Answer the following questions:
</div>
<div class="Questions">
<ol start="9" style="list-style-type: decimal">
<li><strong>Verify the requirements have been met</strong></li>
</ol>
<a href = "javascript:showhide('Q9')"><span
style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="Q9" style="display:none;">
<ul>
<li><p>Requirement: <strong>A simple random sample was drawn from the
population.</strong></p>
<p>As explained previously, the data represent a convenience sample of
patients, who have been matched based on their overall health and their
current ailment. In fact, if we go back to the original research article
and read, we find that they were college students Dr. Wayne Campbell
recruited for his protein study. They were people that were willing to
endure the conditions of the study for 3 months for $600. So we fail the
requirement of having a simple random sample, but we will pretend that
this group of people is representative of the entire adult population in
the U.S.</p></li>
<li><p>Requirement: <strong>The sample mean (<span
class="math inline">\(\bar{d}\)</span>) is normally
distributed.</strong></p>
<p>The sample size is large (<span class="math inline">\(n =
52\)</span>), so the mean of the differences <span
class="math inline">\(\bar d\)</span> will be approximately normally
distributed by virtue of the Central Limit Theorem.</p></li>
</ul>
</div>
<p><br></p>
<ol start="10" style="list-style-type: decimal">
<li><strong>Give the test statistic and its value</strong></li>
</ol>
<a href = "javascript:showhide('Q10')"><span
style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="Q10" style="display:none;">
<ul>
<li>The test statistic for a test for two means with paired data is a
<span class="math inline">\(t\)</span>.</li>
</ul>
<pre class="r"><code>t.test(hospital_infections$difference, 
       mu = 0, 
       alternative = &quot;greater&quot;,
       conf.level = 0.95)</code></pre>
<pre><code>## 
##  One Sample t-test
## 
## data:  hospital_infections$difference
## t = 5.935, df = 51, p-value = 1.296e-07
## alternative hypothesis: true mean is greater than 0
## 95 percent confidence interval:
##  8.171035      Inf
## sample estimates:
## mean of x 
##  11.38462</code></pre>
<p><span class="math display">\[t = 5.935\]</span></p>
</div>
<p><br></p>
<ol start="11" style="list-style-type: decimal">
<li><strong>State the degrees of freedom</strong></li>
</ol>
<a href = "javascript:showhide('Q11')"><span
style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="Q11" style="display:none;">
<center>
<span class="math display">\[
df = 51
\]</span>
</center>
</div>
<p><br></p>
<ol start="13" style="list-style-type: decimal">
<li><strong>Find the <span class="math inline">\(P\)</span>-value and
compare it to the level of significance</strong></li>
</ol>
<a href = "javascript:showhide('Q13')"><span
style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="Q13" style="display:none;">
<p>The p-value can be found in the R output. As a reminder, scientific
notation of <span class="math inline">\(1.296e^{-7}\)</span> is
equivalent to <span class="math inline">\(1.296 \times 10^{-7}\)</span>.
The <span class="math inline">\(-7\)</span> tells us to move the decimal
place to the left seven times, causing the number to change from <span
class="math inline">\(1.296\)</span> to <span
class="math inline">\(0.0000001296\)</span>. So, translating what the R
output gave us gives</p>
<center>
<span class="math display">\[
P\textrm{-value} = 1.296e^{-7} = 0.0000001296 &lt; 0.05 = \alpha
\]</span>
</center>
</div>
<p><br></p>
<ol start="14" style="list-style-type: decimal">
<li><strong>State your decision</strong></li>
</ol>
<a href = "javascript:showhide('Q14')"><span
style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="Q14" style="display:none;">
<ul>
<li>Since the <span class="math inline">\(P\)</span>-value is less than
the level of significance, we reject the null hypothesis.</li>
</ul>
</div>
<p> </p>
</div>
<p><br></p>
<p><img src = "Images/Step5.png"></p>
<div class="QuestionsHeading">
Answer the following questions:
</div>
<div class="Questions">
<ol start="15" style="list-style-type: decimal">
<li><strong>Present your conclusion in an English sentence, relating the
result to the context of the problem</strong></li>
</ol>
<a href = "javascript:showhide('Q15')"><span
style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="Q15" style="display:none;">
<ul>
<li>There is sufficient evidence to suggest that the mean duration of
hospital stays is increased when a patient develops a nosocomial
infection.</li>
</ul>
</div>
<p> </p>
</div>
<p><br></p>
</div>
<div id="additional-worked-examples" class="section level3">
<h3>Additional Worked Examples</h3>
<p>Viewing additional examples can help your understanding. Click on the
link below to see two more examples of hypothesis tests.</p>
<a href = "javascript:showhide('ae')"><span
style="font-size:8pt;">Show/Hide Additional Examples</span></a>
<div id = "ae" style = "display:none;">


<p><img src = "Images/StepsAll.png"></p>
<div id="effect-of-stressful-classical-music-on-your-metabolism"
class="section level4">
<h4>Effect of Stressful Classical Music on Your Metabolism</h4>
<p><img src = "Images/Step1.png"></p>
<p><strong>Summarize the relevant background information</strong></p>
<p>Obesity is a growing problem worldwide. Many scientists are seeking
creative solutions to trim down this epidemic. Reduced energy
expenditure is a potential cause of obesity.</p>
<p>Resting Energy Expenditure (REE) is defined as the amount of energy a
person would use if resting for 24 hours. In essence, this is the amount
of energy that a person’s body will consume if they do not do any
physical activity. REE is measured in terms of kilo-Joules per day
(kJ/d).</p>
<p>REE accounts for approximately 70 to 80% of all energy that a person
will expend in a day. <!--<cite>Carlsson05</cite>--> If researchers can
find simple, enjoyable activities that will increase REE, it may be
possible to minimize the spread of obesity around the world.</p>
<p>Ebba Carlsson and other researchers in Sweden investigated whether
listening to stressful classical music increases a person’s REE.
<!--<cite>Carlsson05</cite>--> Each subject’s REE was measuring during
silence and again while listening to stressful classical music. Data
representing their results are given in the data frame <code>ree</code>.
You can access this data frame by running the command
<code>load(url("https://byuistats.github.io/M221R/data/L12.RData"))</code>
in R.</p>
<p>Notice that this is not a pre- and post-test, but it is still a test
involving paired data. Two REE measurements were made for each subject:
(1) in silence (<span class="math inline">\(silence\)</span>) and (2)
while listening to stressful classical music (<span
class="math inline">\(stressful\)</span>).</p>
<p><strong>State the null and alternative hypotheses and the level of
significance</strong></p>
<p>Since we are testing for an increase in the mean REE, we let <span
class="math inline">\(d = stressful - silence\)</span>. Our alternative
hypothesis will be that <span class="math inline">\(\mu_d &gt;
0\)</span>. The null and alternative hypotheses are: <span
class="math display">\[
\begin{align}
H_0: &amp;~~ \mu_d = 0 \\
H_a: &amp;~~ \mu_d &gt; 0
\end{align}
\]</span></p>
<p>We will use the <span class="math inline">\(\alpha = 0.1\)</span>
level of significance.</p>
<p><img src = "Images/Step2.png"></p>
<p><strong>Describe the data collection procedures</strong></p>
<p>The REE was measured by a technique called “indirect calorimetry”
using a Deltatrac II Metabolic Monitor. <!--<cite>Carlsson05</cite>-->
The REE was measured twice for each person: while the person was (1)
resting in silence or (2) resting while listening to stressful classical
music. These trials were conducted in random order. Some of the subjects
had the “silence” treatment first, and others had the “stressful”
treatment first.</p>
<p><img src = "Images/Step3.png"></p>
<div class="QuestionsHeading">
Answer the following questions:
</div>
<div class="Questions">
<ol start="16" style="list-style-type: decimal">
<li>We will define the difference in REE by subtracting the REE in
silence from the REE while listening to stressful classical music. If
listening to stressful classical music actually increases the mean REE,
would you expect the value of the difference to be typically positive or
negative?</li>
</ol>
<a href = "javascript:showhide('Q16')"><span
style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="Q16" style="display:none;">
<ul>
<li>If the REE is higher while listening to classical music than while
resting in silence, we would expect the value of the difference to be
positive. In other words the following difference would tend to be
positive:</li>
</ul>
<p><span class="math display">\[
difference stressful - silence
\]</span></p>
</div>
<p><br></p>
<ol start="17" style="list-style-type: decimal">
<li>Compute the difference in REE for each person. What is the value of
the difference for the first person listed in the data file?</li>
</ol>
<a href = "javascript:showhide('Q17')"><span
style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="Q17" style="display:none;">
<p>First, load the <code>ree</code> data into RStudio.</p>
<p>Then, compute the differences using the command:</p>
<pre class="r"><code>ree$difference &lt;- ree$stressful - ree$silence</code></pre>
<p>To look at the differences, simply type</p>
<pre class="r"><code>ree$difference</code></pre>
<pre><code> [1]   50  240   80  -30  110 -200  190  180  170  190  130   70 -150  -10  170
[16] -150 -110   20  280   20 -250  -70  230   20  130 -160 -160   20   80  -40
[31]  -30 -340  120   10  320  170   30 -220 -230  -80</code></pre>
<p>The first observed difference will be 50 kJ/d.</p>
</div>
<p><br></p>
<p><strong>Give the relevant summary statistics</strong></p>
<ol start="18" style="list-style-type: decimal">
<li>Report the number of subjects (<span
class="math inline">\(n\)</span>), the mean difference (<span
class="math inline">\(\bar d\)</span>), and the standard deviation of
the differences (<span class="math inline">\(s_d\)</span>).</li>
</ol>
<a href = "javascript:showhide('Q18')"><span
style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="Q18" style="display:none;">
<pre class="r"><code>favstats(ree$difference)</code></pre>
<pre><code>  min    Q1 median  Q3 max mean       sd  n missing
 -340 -87.5     20 140 320   20 159.5024 40       0</code></pre>
<p><span class="math display">\[
\begin{align}
n&amp; = 40\\
\bar d &amp; = 20~\text{kJ/d}\\
s_d &amp; = 159.5~\text{kJ/d}
\end{align}
\]</span></p>
</div>
<p><br></p>
<p><strong>Visualize the data</strong></p>
<ol start="19" style="list-style-type: decimal">
<li>Create a histogram and boxplot of the differences.</li>
</ol>
<a href = "javascript:showhide('Q19')"><span
style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="Q19" style="display:none;">
<pre class="r"><code>hist(ree$difference, 
     main = &quot;Effect of Classical Music on Energy&quot;, 
     xlab = &quot;Resting Energy Expenditure (Stressful - Silence)&quot;, 
     col = &quot;darkorchid&quot;) </code></pre>
<p><img src="Lesson12_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<pre class="r"><code>boxplot(ree$difference,
        horizontal = TRUE,
        main = &quot;Effect of Classical Music on Energy&quot;,
        xlab = &quot;Resting Energy Expenditure (Stressful - Silence)&quot;,
        col = &quot;darkorchid&quot;) </code></pre>
<p><img src="Lesson12_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
</div>
<p><br></p>
</div>
<p><br></p>
<p><img src = "Images/Step4.png"></p>
<p><strong>Verify the requirements have been met</strong></p>
<ul>
<li><p>Requirment: <strong>A simple random sample was drawn from the
population.</strong></p>
<p>We can consider the sample representative of the population even
though it was not a simple random sample.<br />
</p></li>
<li><p>Requirement: <strong>The sample mean (<span
class="math inline">\(\bar{d}\)</span>) is normally
distributed.</strong></p>
<p>Because our sample size (<span class="math inline">\(n = 40\)</span>)
of differences is greater than 30, we can be sure the sampling
distribution of <span class="math inline">\(\bar d\)</span> will be
normal by the Central Limit Theorem.</p></li>
</ul>
<p>The requirements for this test appear to have been satisfied.</p>
<div class="QuestionsHeading">
Answer the following questions:
</div>
<div class="Questions">
<ol start="20" style="list-style-type: decimal">
<li><strong>Give the test statistic and its value</strong></li>
</ol>
<a href = "javascript:showhide('Q20')"><span
style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="Q20" style="display:none;">
<ul>
<li>The test statistic for a test for two means with paired data is a
<span class="math inline">\(t\)</span>.</li>
</ul>
<pre class="r"><code>t.test(ree$difference, 
       mu = 0, 
       alternative = &quot;greater&quot;,
       conf.level = 0.95)</code></pre>
<pre><code>
    One Sample t-test

data:  ree$difference
t = 0.79304, df = 39, p-value = 0.2163
alternative hypothesis: true mean is greater than 0
95 percent confidence interval:
 -22.49179       Inf
sample estimates:
mean of x 
       20 </code></pre>
<p><span class="math display">\[t = 0.793\]</span></p>
</div>
<p><br></p>
<ol start="21" style="list-style-type: decimal">
<li><strong>State the degrees of freedom</strong></li>
</ol>
<a href = "javascript:showhide('Q21')"><span
style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="Q21" style="display:none;">
<center>
<span class="math display">\[
df = 39
\]</span>
</center>
</div>
<ol start="22" style="list-style-type: decimal">
<li><strong>Mark the test statistic and <span
class="math inline">\(P\)</span>-value on a graph of the sampling
distribution</strong></li>
</ol>
<a href = "javascript:showhide('Q22')"><span
style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="Q22" style="display:none;">
<ul>
<li>The test statistic is plotted on the horizontal axis. The degrees of
freedom are entered into the top box. “The <span
class="math inline">\(P\)</span>-value is shaded in green. The same
value can be found in the R output above.</li>
</ul>
<center>
<img src = "Images/REE-Applet.png">
</center>
</div>
<p><br></p>
<ol start="23" style="list-style-type: decimal">
<li><strong>Find the <span class="math inline">\(P\)</span>-value and
compare it to the level of significance</strong></li>
</ol>
<a href = "javascript:showhide('Q23')"><span
style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="Q23" style="display:none;">
<center>
<span class="math inline">\(P\textrm{-value} = 0.2163 &gt; 0.1 =
\alpha\)</span>
</center>
<ul>
<li>Notice that the <span class="math inline">\(P\)</span>-value is half
as large for a one-tailed test as it would have been for a two-tailed
test. Since we have a one-sided alternative hypothesis, we are only
interested in the right tail of the <span
class="math inline">\(t\)</span>-distribution.</li>
</ul>
</div>
<p><br></p>
<ol start="24" style="list-style-type: decimal">
<li><strong>State your decision</strong></li>
</ol>
<a href = "javascript:showhide('Q24')"><span
style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="Q24" style="display:none;">
<ul>
<li>Since the <span class="math inline">\(P\)</span>-value is greater
than the level of significance, we fail to reject the null
hypothesis.</li>
</ul>
</div>
<p> </p>
</div>
<p><br></p>
<p><img src = "Images/Step5.png"></p>
<div class="QuestionsHeading">
Answer the following questions:
</div>
<div class="Questions">
<ol start="25" style="list-style-type: decimal">
<li><strong>Present your conclusion in an English sentence, relating the
result to the context of the problem</strong></li>
</ol>
<a href = "javascript:showhide('Q25')"><span
style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="Q25" style="display:none;">
<ul>
<li>There is insufficient evidence to suggest that the mean REE is
<em>increased</em> by listening to stressful classical music. Lying
still and listening to stressful classical music is probably not the
best way to increase your metabolism!</li>
</ul>
</div>
<p> </p>
</div>
<p><br></p>
<p>Note that we did not say we “accept” the null hypothesis. We do not
know that listening to stressful classical music has no effect on a
person’s REE. Based on the data available to us, we were not able to
reject the assertion that this type of music does not increase the mean
REE.   <br></p>
<p><img src = "Images/StepsAll.png"></p>
</div>
<div id="cost-of-airline-tickets" class="section level4">
<h4>Cost of Airline Tickets</h4>
<p><img src = "Images/Step1.png"></p>
<p><strong>Summarize the relevant background information</strong></p>
<p>Pressures of supply and demand act directly on the prices for an
airline ticket. As the seats available on the plane begin to fill,
airlines raise the price. If seats on a flight do not sell well, an
airline may discount the tickets or even cancel the flight. Business
travelers frequently demand travel booked on short notice. They must pay
the current price. Typically, tourists book their flights well in
advance, hoping to buy tickets before the price rises. We will consider
the cost of a one-way ticket from London’s Heathrow Airport to a variety
of destinations in Europe.</p>
<p>Allie Henrich, a BYU-Idaho student, compared the lowest published
ticket prices of one-way flights from Heathrow to various destinations
in Europe. Using Travelocity.com, she recorded the lowest published
fares for nonstop midweek flights booked either 14 days in advance or 90
days in advance. The prices (in US dollars) are given in the file
<code>direct_flight_costs</code>. You can access this data frame by
running the command
<code>load(url("https://byuistats.github.io/M221R/data/L12.RData"))</code>
in R.<br />
Notice that for some destinations, flights were not available.</p>
<p>The data are paired, because we are measuring the costs twice for
each city. The 14-day ticket price is paired with the 90-day price for
each city.</p>
<p>We will conduct a hypothesis test to determine if there is a
difference in the cost of the nonstop flights when tickets are purchased
14 days in advance compared to 90 days in advance. We will use the 0.01
level of significance.</p>
<div class="QuestionsHeading">
Answer the following questions:
</div>
<div class="Questions">
<ol start="26" style="list-style-type: decimal">
<li><strong>State the null and alternative hypotheses and the level of
significance</strong></li>
</ol>
<a href = "javascript:showhide('Q26')"><span
style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="Q26" style="display:none;">
<center>
<span class="math display">\[
\begin{array}{1cl}
H_0:\mu_d = 0 \\
H_a:\mu_d \ne 0 \\
\alpha = 0.01
\end{array}
\]</span>
</center>
</div>
<p> </p>
</div>
<p><br></p>
<p><img src = "Images/Step2.png"></p>
<div class="QuestionsHeading">
Answer the following questions:
</div>
<div class="Questions">
<ol start="27" style="list-style-type: decimal">
<li><strong>Describe the data collection procedures</strong></li>
</ol>
<a href = "javascript:showhide('Q27')"><span
style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="Q27" style="display:none;">
<ul>
<li>The data were collected using the website Travelocity.com. The
lowest advertized ticket prices were recorded for nonstop flights from
Heathrow Airport. All prices were recorded in US dollars. Data are
provided on the cost of a nonstop ticket purchased with 14 days notice
compared to 90 days notice.</li>
<li>We will compute the difference in the costs for each destination.
Some destinations did not include both flight options. In this case, the
difference is not computed and the data are omitted from the
analysis.</li>
</ul>
</div>
<p> </p>
</div>
<p><br></p>
<p><img src = "Images/Step3.png"></p>
<div class="QuestionsHeading">
Answer the following questions:
</div>
<div class="Questions">
<ol start="28" style="list-style-type: decimal">
<li><strong>Give the relevant summary statistics</strong></li>
</ol>
<a href = "javascript:showhide('Q28')"><span
style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="Q28" style="display:none;">
<ul>
<li>The differences were computed by subtracting the 90-day price from
the 14-day price. For example, for the Adnan Menderes Airport, we
have</li>
</ul>
<p><span class="math display">\[202.09 - 234.19 = -32.10\]</span></p>
<ul>
<li>You may have chosen to subtract in the opposite order. If so, you
would have obtained a value of <span
class="math inline">\(32.10\)</span> dollars.</li>
</ul>
<p><span class="math display">\[
\begin{align}
n&amp; = 87\\
\bar d &amp; = 24.612\\
s_d &amp; = 136.267
\end{align}
\]</span></p>
<br>
<div class="message Note">
If you defined your difference as the 90-day price minus the 14-day
price, then you would have observed a value of <span
class="math inline">\(\bar d = -24.612\)</span> dollars for the mean of
the differences. You were not instructed on the order in which to
subtract, so this is a correct response. The value for the standard
deviation of the difference and the number of observations (pairs) will
be the same as is given above.
</div>
<p><br> <br></p>
</div>
<p><br></p>
<ol start="29" style="list-style-type: decimal">
<li><strong>Make an appropriate graph to illustrate the
data</strong></li>
</ol>
<a href = "javascript:showhide('Q29')"><span
style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="Q29" style="display:none;">
<pre class="r"><code>direct_flight_costs$difference &lt;- direct_flight_costs$fourteen_days - direct_flight_costs$ninety_days
hist(direct_flight_costs$difference, 
     col = &quot;tan3&quot;,
     xlab = &quot;Difference in Dollar Cost (14 Days - 90 Days)&quot;,
     main = &quot;Direct Flight Costs&quot;,
     breaks = 30)</code></pre>
<p><img src="Lesson12_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<ul>
<li>If you defined your difference as the 90-day price minus the 14-day
price, then you would have the following histogram instead:</li>
</ul>
<pre class="r"><code>direct_flight_costs$difference2 &lt;- direct_flight_costs$ninety_days - direct_flight_costs$fourteen_days
hist(direct_flight_costs$difference2, 
     col = &quot;brown3&quot;,
     xlab = &quot;Difference in Dollar Cost (90 Days - 14 Days)&quot;,
     main = &quot;Direct Flight Costs&quot;,
     breaks = 30)</code></pre>
<p><img src="Lesson12_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
</div>
<p> </p>
</div>
<p><br></p>
<p><img src = "Images/Step4.png"></p>
<div class="QuestionsHeading">
Answer the following questions:
</div>
<div class="Questions">
<ol start="30" style="list-style-type: decimal">
<li><strong>Verify the requirements have been met</strong></li>
</ol>
<a href = "javascript:showhide('Q30')"><span
style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="Q30" style="display:none;">
<ul>
<li>This is not a simple random sample of airports. Rather, the sample
was chosen from the list of the busiest airports in Europe. However, we
are not making an inference on the airports but on the difference in the
cost of the flights.</li>
<li>The sample size is large, so we can conclude that the sample mean,
<span class="math inline">\(\bar d\)</span> is normally distributed by
virtue of the Central Limit Theorem.</li>
</ul>
</div>
<p><br></p>
<ol start="31" style="list-style-type: decimal">
<li><strong>Give the test statistic and its value</strong></li>
</ol>
<a href = "javascript:showhide('Q31')"><span
style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="Q31" style="display:none;">
<ul>
<li>The test statistic for a test for two means with paired data is a
<span class="math inline">\(t\)</span>.</li>
</ul>
<p><span class="math display">\[t = 1.685\]</span></p>
<ul>
<li>If you computed the difference as the 90-day price minus the 14-day
price, the value of your test statistic is <span
class="math inline">\(-1.685\)</span>.</li>
</ul>
</div>
<p><br></p>
<ol start="32" style="list-style-type: decimal">
<li><strong>State the degrees of freedom</strong></li>
</ol>
<a href = "javascript:showhide('Q32')"><span
style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="Q32" style="display:none;">
<center>
<span class="math display">\[
df = 86
\]</span>
</center>
</div>
<p><br></p>
<ol start="33" style="list-style-type: decimal">
<li><strong>Mark the test statistic and <span
class="math inline">\(P\)</span>-value on a graph of the sampling
distribution</strong></li>
</ol>
<a href = "javascript:showhide('Q33')"><span
style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="Q33" style="display:none;">
<ul>
<li>The test statistic is plotted on the horizontal axis. The degrees of
freedom are entered into the top box. The <span
class="math inline">\(P\)</span>-value is shaded in green. The same
value can be found in the R output of the <code>t.test(...)</code>.</li>
</ul>
<center>
<img src = "Images/DirectFlightCosts-Applet.png">
</center>
</div>
<p><br></p>
<ol start="34" style="list-style-type: decimal">
<li><strong>Find the <span class="math inline">\(P\)</span>-value and
compare it to the level of significance</strong></li>
</ol>
<a href = "javascript:showhide('Q34')"><span
style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="Q34" style="display:none;">
<center>
<span class="math display">\[
P\textrm{-value} = 0.096 &gt; 0.01 = \alpha
\]</span>
</center>
<p>The <span class="math inline">\(P\)</span>-value will be 0.096, no
matter what order you subtracted the values.</p>
</div>
<p><br></p>
<ol start="35" style="list-style-type: decimal">
<li><strong>State your decision</strong></li>
</ol>
<a href = "javascript:showhide('Q35')"><span
style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="Q35" style="display:none;">
<p>Since the <span class="math inline">\(P\)</span>-value is greater
than the level of significance, we fail to reject the null
hypothesis.</p>
</div>
<p> </p>
</div>
<p><br></p>
<p><img src = "Images/Step5.png"></p>
<div class="QuestionsHeading">
Answer the following questions:
</div>
<div class="Questions">
<ol start="36" style="list-style-type: decimal">
<li><strong>Present your conclusion in an English sentence, relating the
result to the context of the problem</strong></li>
</ol>
<a href = "javascript:showhide('Q36')"><span
style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="Q36" style="display:none;">
<ul>
<li>There is insufficient evidence to suggest that there is a difference
in the mean cost of airline tickets 14-days versus 90-days in
advance.</li>
</ul>
</div>
<p> </p>
</div>
<p><br></p>
</div>
</div>
</div>
<div id="confidence-intervals" class="section level2">
<h2>Confidence Intervals</h2>
<p>We can compute a confidence interval for the true mean of the
differences for paired data. After the differences between two paired
data sets have been calculated, we can create a confidence interval for
the true mean of the differences. To do this, we follow the instructions
for creating a confidence interval for a one mean with <span
class="math inline">\(\sigma\)</span> unknown, but we use the column of
differences as the data set.</p>
<p>The requirements for creating a confidence interval for the
difference of means are the same as the requirements for the hypothesis
test. We require that:</p>
<ul>
<li>A simple random sample was drawn from the population</li>
<li>The mean of the differences is normally distributed</li>
</ul>
<p>  <img src = "Images/StepsAll.png"></p>
<p><img src = "Images/PineBeetleDamage-1441150-LG.png"></p>
<div id="mountain-pine-beetle-attacks" class="section level3">
<h3>Mountain Pine Beetle Attacks</h3>
<p><img src = "Images/Step1.png"></p>
<p><strong>Summarize the relevant background information</strong></p>
<p>Mountain pine beetles are small insects that bore into the bark of
trees. The female beetles that first infest the tree emit pheromones to
attract other beetles. In response to the pheromones, many beetles bore
into the tree and ultimately kill it. The insects can destroy large tree
stands within one year.</p>
<p>Lodgepole pine (<em>Pinus contorta</em> Dougl.ex Loud.) are
particularly susceptible to mountain pine beetle (<em>Dendroctonus
ponderosae</em> Hopkins) outbreaks. The image above shows the
destruction that can be caused by these insects. The large brown patches
are pines that have been killed by the beetles.</p>
<div class="QuestionsHeading">
Answer the following questions:
</div>
<div class="Questions">
<ol start="37" style="list-style-type: decimal">
<li>The mountain pine beetle threatens many forests in the United
States. These tiny insects are only 0.5 cm long–about the size of a
grain of rice. This photo of a mountain pine beetle is magnified
greatly. These little creatures can destroy a large, healthy forest. Can
you think of a spiritual parallel?</li>
</ol>
<p><img src = "Images/MountainPineBeetle2-1306004.png"></p>
<a href = "javascript:showhide('Q37')"><span
style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="Q37" style="display:none;">
<ul>
<li>There are many great diverse answers that could be presented. Please
share your thoughts with someone in your group.</li>
</ul>
<!--: The story of President Hinckley’s axe head in the notch of a tree provides a similar analogy.-->
</div>
<p> </p>
</div>
<p><br></p>
<p><img src = "Images/Step2.png"></p>
<p><strong>Describe the data collection procedures</strong></p>
<p>In a study conducted in the Arapaho National Forest in Colorado,
researchers from the USDA Forest Service studied the effect of pine
beetle outbreaks on the average number of trees in an area.
<!--<cite>Klutsch09</cite>--> The researchers counted the number of
established trees per hectare before a pine beetle outbreak and seven
years after an outbreak. (One hectare is an area of 100 meters by 100
meters.) Data representative of their observations are given in the data
frame <code>pine_beetle</code>. You can access these data by running the
command
<code>load(url("https://byuistats.github.io/M221R/data/L12.RData"))</code>
in R.</p>
<p><img src = "Images/Step3.png"></p>
<div class="QuestionsHeading">
Answer the following questions:
</div>
<div class="Questions">
<p><strong>Give the relevant summary statistics</strong></p>
<ol start="38" style="list-style-type: decimal">
<li>Find the mean and standard deviation of the number of trees per
hectare <em>before</em> the pine beetle outbreak. How would you describe
the density of the trees in this forest? Express this in terms that make
sense to you.</li>
</ol>
<a href = "javascript:showhide('Q38')"><span
style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="Q38" style="display:none;">
<pre class="r"><code>favstats(pine_beetle$before)</code></pre>
<pre><code>   min      Q1  median       Q3    max     mean       sd   n missing
 894.6 989.175 1029.85 1060.025 1195.9 1028.406 57.03149 170       0</code></pre>
<ul>
<li>The mean, given in the summary output above, was 1028.41 trees per
hectare and the standard deviation was 57.03 trees per hectare. Note
that the values were rounded to two decimal places, since the data were
given to one decimal place.</li>
<li>Answers will vary regarding the description of the density. Here is
one possible response.</li>
<li>There is roughly one tree every <span
class="math inline">\(\frac{100 \times 100}{1028.41} = 9.7\)</span>
square meters. In other words, on average, each tree would have a space
of about <span class="math inline">\(\sqrt{9.7} = 3.1\)</span> meters
long and 3.1 meters wide in which to grow.</li>
</ul>
</div>
<p><br></p>
<ol start="39" style="list-style-type: decimal">
<li>Repeat question 38 for the number of trees per hectare
<em>after</em> the outbreak.</li>
</ol>
<a href = "javascript:showhide('Q39')"><span
style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="Q39" style="display:none;">
<pre class="r"><code>favstats(pine_beetle$after)</code></pre>
<pre><code>   min      Q1 median    Q3   max     mean       sd   n missing
 429.9 563.725 596.45 627.5 687.2 592.8712 45.30785 170       0</code></pre>
<ul>
<li>The mean was 592.87 trees per hectare and the standard deviation was
45.31 trees per hectare.</li>
<li>Answers will vary regarding the description of the density. Here is
one possible response.</li>
<li>The trees are about half as dense as they were before the pine
beetle infestation. About <span
class="math inline">\(\frac{592.87}{1028.41} = 0.58 = 58\%\)</span> of
the trees remained, so <span class="math inline">\(100\% - 58\% =
42\%\)</span> of the trees were killed by the pine beetles!</li>
</ul>
</div>
<p><br></p>
<ol start="40" style="list-style-type: decimal">
<li>Find the differences by subtracting the “before” counts from the
“after” counts:</li>
</ol>
<p><span class="math display">\[difference = after - before\]</span>
<strong>Be careful to match the order of subtraction.</strong></p>
<ul>
<li>For these differences, report the mean, the standard deviation, and
the sample size.</li>
</ul>
<a href = "javascript:showhide('Q40')"><span
style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="Q40" style="display:none;">
<pre class="r"><code>pine_beetle$difference &lt;- pine_beetle$after - pine_beetle$before
favstats(pine_beetle$difference)</code></pre>
<pre><code>    min       Q1  median       Q3    max      mean       sd   n missing
 -517.3 -441.475 -431.35 -425.275 -402.6 -435.5347 17.08227 170       0</code></pre>
<center>
<strong>Summary Statistics:</strong>
</center>
<table>
<thead>
<tr class="header">
<th align="center"> </th>
<th align="center"> </th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Mean:</td>
<td align="center"><span class="math inline">\(\bar d =
-435.535\)</span></td>
</tr>
<tr class="even">
<td align="center">Standard Deviation:</td>
<td align="center"><span class="math inline">\(s_d =
17.082\)</span></td>
</tr>
<tr class="odd">
<td align="center">Sample Size:</td>
<td align="center"><span class="math inline">\(n = 170\)</span></td>
</tr>
</tbody>
</table>
</div>
<p><br></p>
<p><strong>Make an appropriate graph to illustrate the data</strong></p>
<ol start="41" style="list-style-type: decimal">
<li>Create a histogram and boxplot of the differences in the density of
the trees.</li>
</ol>
<a href = "javascript:showhide('Q41')"><span
style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="Q41" style="display:none;">
<pre class="r"><code>hist(pine_beetle$difference, 
     main = &quot;Pine Beetle Outbreaks&quot;, 
     xlab = &quot;Difference in Tree Density (After - Before)&quot;, 
     col = &quot;darkolivegreen4&quot;)</code></pre>
<p><img src="Lesson12_files/figure-html/unnamed-chunk-26-1.png" width="672" /></p>
<pre class="r"><code>boxplot(pine_beetle$difference,
        horizontal = TRUE,
        main = &quot;Pine Beetle Outbreaks&quot;,
        xlab = &quot;Difference in Tree Density (After - Before)&quot;,
        col = &quot;darkolivegreen4&quot;)</code></pre>
<p><img src="Lesson12_files/figure-html/unnamed-chunk-27-1.png" width="672" /></p>
</div>
<p> </p>
</div>
<p><br></p>
<p><img src = "Images/Step4.png"></p>
<p>To create a confidence interval for the true mean of the differences
<span class="math inline">\(\mu_d\)</span> in R, use the following.</p>
</div>
<div id="r-instructions-for-confidence-intervals"
class="section level3">
<h3>R Instructions for Confidence Intervals</h3>
<div class="SoftwareHeading">
R Instructions
</div>
<div class="Software">
<p><strong>To calculate confidence intervals for the true mean of the
difference in R, do the following</strong>:</p>
<ul>
<li>Read in the data to RStudio if you haven’t already: <a
href="./data/pine_beetle.xslx">pine_beetle</a></li>
<li>Compute the differences if you haven’t already:</li>
</ul>
<pre class="r"><code>pine_beetle$difference &lt;- pine_beetle$after - pine_beetle$before</code></pre>
<ul>
<li>Use the code
<code>t.test(pine_beetle$difference, conf.level = 0.95)</code> to set
the desired confidence level and create the confidence interval.</li>
</ul>
<pre class="r"><code>t.test(pine_beetle$difference, conf.level = 0.95)</code></pre>
<pre><code>
    One Sample t-test

data:  pine_beetle$difference
t = -332.43, df = 169, p-value &lt; 2.2e-16
alternative hypothesis: true mean is not equal to 0
95 percent confidence interval:
 -438.1211 -432.9483
sample estimates:
mean of x 
-435.5347 </code></pre>
<p>The row of the output shown above called “95 percent confidence
interval:” shows the <strong>lower bound</strong> as -438.1211 and the
<strong>upper bound</strong> as -432.9483.</p>
<p><br></p>
</div>
<p><br></p>
<div class="QuestionsHeading">
Answer the following questions:
</div>
<div class="Questions">
<ol start="42" style="list-style-type: decimal">
<li><strong>Verify the requirements have been met.</strong></li>
</ol>
<a href = "javascript:showhide('Q42')"><span
style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="Q42" style="display:none;">
<ul>
<li><p>Requirement: <strong>A simple random sample was drawn from the
population.</strong></p>
<p>It is not explicitly stated, but we assume the plots of land were
selected at random.</p></li>
<li><p>Requirement: <strong>The sample mean (<span
class="math inline">\(\bar{d}\)</span>) is normally
distributed.</strong></p>
<p>For the pine beetle data, the histogram indicates that the data are
not normally distributed. However, since the sample size is large (<span
class="math inline">\(n = 170\)</span>), we can know by the Central
Limit Theorem that the sample mean <span
class="math inline">\(\bar{d}\)</span> is normally distributed despite
the skew in the data.</p></li>
</ul>
<p>The requirements for creating the confidence interval seem to be
satisfied.</p>
</div>
<p><br></p>
<ol start="43" style="list-style-type: decimal">
<li><strong>Find the confidence interval</strong>. Use the 95% level of
confidence.</li>
</ol>
<a href = "javascript:showhide('Q43')"><span
style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="Q43" style="display:none;">
<pre class="r"><code>t.test(pine_beetle$difference, conf.level = 0.95)</code></pre>
<pre><code>
    One Sample t-test

data:  pine_beetle$difference
t = -332.43, df = 169, p-value &lt; 2.2e-16
alternative hypothesis: true mean is not equal to 0
95 percent confidence interval:
 -438.1211 -432.9483
sample estimates:
mean of x 
-435.5347 </code></pre>
<center>
<span class="math inline">\((-438.121,~ -432.948)\)</span>
</center>
</div>
<p> </p>
</div>
<p><br></p>
<p><img src = "Images/Step5.png"></p>
<p><strong>Present your observations in an English sentence, relating
the result to the context of the problem</strong></p>
<p>Interpret the confidence interval we created. We are 95% confident
that the true mean change in the number of trees per hectare after a
pine beetle outbreak is between <span
class="math inline">\(-438.121\)</span> and <span
class="math inline">\(-432.948\)</span> trees per hectare. Stated
differently, we are 95% confident that the true mean <em>decrease</em>
in the number of trees per hectare after a pine beetle outbreak is
between <span class="math inline">\(432.948\)</span> and <span
class="math inline">\(438.121\)</span> trees per hectare.</p>
<p> </p>
<p><img src = "Images/StepsAll.png"></p>
</div>
<div id="sleep-inducing-drugs" class="section level3">
<h3>Sleep-Inducing Drugs</h3>
<p>In this example, we explore how to handle missing values in the
data.</p>
<p><img src = "Images/Step1.png"></p>
<p><strong>Summarize the relevant background information</strong></p>
<p>In William Sealy Gosset’s landmark paper on the <span
class="math inline">\(t\)</span>-distribution, he cites data on a
sleep-inducing drug. In a paper published in 1905, Arthur R. Cushny and
A. Roy Peebles reported the effect of Laevorotatory Hyoscyamine
Hydrobromate (L-Hyoscyamine) on the length of time that people sleep
before waking. <!-- cite{Cushny05} --> The primary research question is:
does L-Hyoscyamine impact the mean amount of time that people sleep? We
will compute a 90% confidence for the true mean difference in the
times.</p>
<p><img src = "Images/Step2.png"></p>
<p><strong>Describe the data collection procedures</strong></p>
<p>Eleven subjects were included in the study. At the start of the
study, the researchers observed the average length of time that each of
the participants slept before waking. Later, each subject was given 0.6
mg of L-Hyoscyamine and the duration of uninterrupted sleep was again
measured.</p>
<p>The difference in the amount of time each person slept was computed
by subtracting the amount of time the subjects slept when taking the
drug minus the sleep duration with no drug. The data are given in the
file <code>sleep_drug</code>. You can access this data frame by running
the command
<code>load(url("https://byuistats.github.io/M221R/data/L12.RData"))</code>
in R. After reading in these data, run the following to compute the
column of differences:</p>
<pre class="r"><code>sleep_drug$difference = sleep_drug$treatment - sleep_drug$control</code></pre>
<p>Run the command <code>View(sleep_drug)</code> to examine the data
file.</p>
<p>Notice that the “control” data for Subject #11 is missing. It is not
possible to compute a difference for this person, so their data will be
omitted from our analysis. For this analysis, we will use the remaining
<span class="math inline">\(n = 10\)</span> observations.</p>
<p><img src = "Images/Step3.png"></p>
<div class="QuestionsHeading">
Answer the following questions:
</div>
<div class="Questions">
<p><strong>Give the relevant summary statistics</strong></p>
<ol start="44" style="list-style-type: decimal">
<li>Report the mean, standard deviation, and sample size for the
differences.</li>
</ol>
<a href = "javascript:showhide('Q44')"><span
style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="Q44" style="display:none;">
<p>We use the following command</p>
<pre class="r"><code>favstats(sleep_drug$difference)</code></pre>
<pre><code>##   min     Q1 median  Q3 max mean      sd  n missing
##  -1.6 -0.175   0.35 1.7 3.7 0.75 1.78901 10       1</code></pre>
<center>
<strong>Summary Statistics:</strong>
</center>
<table>
<thead>
<tr class="header">
<th align="center"> </th>
<th align="center"> </th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Mean:</td>
<td align="center"><span class="math inline">\(\bar d = 0.750\)</span>
hours</td>
</tr>
<tr class="even">
<td align="center">Standard Deviation:</td>
<td align="center"><span class="math inline">\(s_d = 1.789\)</span>
hours</td>
</tr>
<tr class="odd">
<td align="center">Sample Size:</td>
<td align="center"><span class="math inline">\(n = 10\)</span></td>
</tr>
</tbody>
</table>
</div>
<p><br></p>
<p><strong>Make an appropriate graph to illustrate the data</strong></p>
<ol start="45" style="list-style-type: decimal">
<li>Create a graph of the differences in the hours of sleep.</li>
</ol>
<a href = "javascript:showhide('Q45')"><span
style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="Q45" style="display:none;">
<p>Here is a histogram and a boxplot of the data:</p>
<pre class="r"><code>hist(sleep_drug$difference,
     col = &quot;brown3&quot;,
     xlab = &quot;Difference in Hours of Sleep&quot;,
     main = &quot;Slee Inducing Drugs Study&quot;)</code></pre>
<p><img src="Lesson12_files/figure-html/unnamed-chunk-33-1.png" width="672" /></p>
<pre class="r"><code>boxplot(sleep_drug$difference, 
        col = &quot;brown3&quot;,
        xlab = &quot;Difference in Hours of Sleep&quot;,
        main = &quot;Slee Inducing Drugs Study&quot;,
        horizontal = TRUE)</code></pre>
<p><img src="Lesson12_files/figure-html/unnamed-chunk-34-1.png" width="672" /></p>
</div>
<p> </p>
</div>
<p><br></p>
<p><img src = "Images/Step4.png"></p>
<div class="QuestionsHeading">
Answer the following questions:
</div>
<div class="Questions">
<ol start="46" style="list-style-type: decimal">
<li><strong>Verify the requirements have been met.</strong></li>
</ol>
<a href = "javascript:showhide('Q46')"><span
style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="Q46" style="display:none;">
<ul>
<li><p>Requirement: <strong>A simple random sample was drawn from the
population.</strong></p>
<p>We assume the subjects represent a random sample from the population
because we do not know otherwise.</p></li>
<li><p>Requirement: <strong>The sample mean (<span
class="math inline">\(\bar{d}\)</span>) is normally
distributed.</strong></p>
<p>Because the sample size is small, with only 10 values, it is hard to
see a shape in a boxplot of the data. However, it is clear that the data
is not strongly skewed. We will move forward, assuming the requirement
of a normal sampling distribution of <span
class="math inline">\(\bar{d}\)</span> is not violated.</p></li>
</ul>
<p>Remember, just like the hypothesis test, this confidence interval for
a mean of differences is robust. That means it is not very sensitive to
the requirements. If they are violated, this interval estimate will
probably still give reasonably good results. We just always check
requirements to make sure we are not working with data that dramatically
violates the requirements because if it did dramatically violate the
requirements, our conclusions could be based on faulty values.</p>
</div>
<p><br></p>
<ol start="47" style="list-style-type: decimal">
<li><strong>Find the confidence interval</strong>. Use the 90% level of
confidence.</li>
</ol>
<a href = "javascript:showhide('Q47')"><span
style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="Q47" style="display:none;">
<pre class="r"><code>t.test(sleep_drug$difference, conf.level = 0.90)</code></pre>
<pre><code>
    One Sample t-test

data:  sleep_drug$difference
t = 1.3257, df = 9, p-value = 0.2176
alternative hypothesis: true mean is not equal to 0
90 percent confidence interval:
 -0.2870553  1.7870553
sample estimates:
mean of x 
     0.75 </code></pre>
<center>
<span class="math inline">\((-0.287, 1.787)\)</span>
</center>
<p>Notice that the <code>t.text</code> function does not have a problem
with the missing value. It computes the output, including the degrees of
freedom (<span class="math inline">\(n-1 = 10 - 1 = 9\)</span>)
correctly.</p>
</div>
<p> </p>
</div>
<p><br></p>
<p><img src = "Images/Step5.png"></p>
<div class="QuestionsHeading">
Answer the following questions:
</div>
<div class="Questions">
<ol start="48" style="list-style-type: decimal">
<li><strong>Present your observations in an English sentence, relating
the result to the context of the problem</strong></li>
</ol>
<a href = "javascript:showhide('Q48')"><span
style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="Q48" style="display:none;">
<ul>
<li>We are 90% confident that the true mean difference in the amount of
time people sleep by taking this drug compared to not taking the drug is
between <span class="math inline">\(-0.287\)</span> hours and <span
class="math inline">\(1.787\)</span> hours.</li>
<li>Notice that 0 is in the confidence interval. This suggests that 0 is
a plausible value for the mean difference in the times. In other words,
the drug does not seem to affect the amount of time people sleep.
L-Hyoscyamine is not an effective sleep aid–at least at these dosage
levels.</li>
</ul>
</div>
<p> </p>
</div>
<p><br></p>
</div>
</div>
<div id="summary" class="section level2">
<h2>Summary</h2>
<div class="SummaryHeading">
Remember…
</div>
<div class="Summary">
<ul>
<li><p>The key characteristic of <strong>dependent samples</strong> (or
<strong>matched pairs</strong>) is that knowing which subjects will be
in group 1 determines which subjects will be in group 2.</p></li>
<li><p>We use slightly different symbols when conducting inference using
dependent samples:</p></li>
</ul>
<div style="padding-left:30px; padding-right:30px;">
<table>
<thead>
<tr class="header">
<th>Symbol</th>
<th>Explanation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(x_1\)</span></td>
<td>Group 1 Values</td>
</tr>
<tr class="even">
<td><span class="math inline">\(x_2\)</span></td>
<td>Group 2 Values</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(d = x_2 - x_1\)</span></td>
<td>Differences</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\bar{d}\)</span></td>
<td>Sample Mean of the Differences</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\mu_d\)</span></td>
<td>True Population Mean of the Differences</td>
</tr>
<tr class="even">
<td><span class="math inline">\(s_d\)</span></td>
<td>Sample Standard Deviation of the Differences</td>
</tr>
</tbody>
</table>
</div>
<ul>
<li><p>When conducting hypothesis tests using dependent samples, the
null hypothesis is always <span class="math inline">\(\mu_d =
0\)</span>, indicating that there is no change between the first
population and the second population. The alternative hypothesis can be
left-tailed (<span class="math inline">\(&lt;\)</span>),
right-tailed(<span class="math inline">\(&gt;\)</span>), or
two-tailed(<span class="math inline">\(\ne\)</span>).</p></li>
<li><p>The R code to perform a paired samples t test requires two steps.
First, the <code>differences</code> must be computed. Second, the
<code>t.test(sleep_drug$difference, mu = 0, alternative = "two.sided")</code>
should be used. Be sure to match the <code>alternative =</code>
statement to either <code>"less"</code>, <code>"greater"</code>, or
<code>"two.sided"</code> so that it matches whatever is stated in the
actual <span class="math inline">\(H_a\)</span> statement.</p></li>
<li><p>The R code to created a confidence interval for the true mean of
the differences, <span class="math inline">\(\mu_d\)</span>, uses
<code>t.test(sleep_drug$difference, conf.level = 0.95)</code> where
<code>conf.level =</code> can be changed to either 0.9 (for a 90%
confidence interval) or 0.99 (for a 99% confidence interval).</p></li>
</ul>
<p><br></p>
</div>
<p><br></p>
</div>
<div id="navigation" class="section level2">
<h2>Navigation</h2>
<center>
<table>
<colgroup>
<col width="38%" />
<col width="30%" />
<col width="30%" />
</colgroup>
<thead>
<tr class="header">
<th align="center"><strong>Previous Reading</strong></th>
<th align="center"><strong>This Reading</strong></th>
<th align="center"><strong>Next Reading</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"><a href="Lesson11.html">Lesson 11: <br> Inference for
One Mean: Sigma Unknown</a></td>
<td align="center">Lesson 12: <br> Inference for Two Means: Paired
Data</td>
<td align="center"><a href="Lesson13.html">Lesson 13: <br> Inference for
Two Means: Independent Samples</a></td>
</tr>
</tbody>
</table>
</center>
</div>

<br />
<hr />
<p>Copyright &copy; 2020 Brigham Young University-Idaho. All rights reserved.</p>



</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
